"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { CalendarDays,CheckCircle2,Clock3,Plus,Trash2,WalletCards } from "lucide-react";
import { MedicalAppShell } from "@/components/medical/MedicalAppShell";
import { useAuth } from "@/context/AuthContext";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { MoneyInput,brlInputToNumber } from "@/components/ui/money-input";
import { hoursBetween,medicalCurrency,shiftStatus,type MedicalShift,type MedicalLink } from "@/lib/medical";

export default function Page(){
 const {supabase,user}=useAuth();
 const [items,setItems]=useState<MedicalShift[]>([]),[links,setLinks]=useState<MedicalLink[]>([]),[open,setOpen]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
 const today=new Date().toISOString().slice(0,10);
 const [form,setForm]=useState({professional_link_id:"",hospital:"",shift_date:today,start_time:"19:00",end_time:"07:00",base_value:"",additional_value:"",expected_payment_date:"",status:"SCHEDULED",notes:""});
 const load=useCallback(async()=>{if(!user)return;const [a,b]=await Promise.all([supabase.from('medical_shifts').select('*').order('shift_date',{ascending:false}),supabase.from('professional_links').select('*').eq('status','ACTIVE')]);if(a.error)setError(a.error.message);else setItems((a.data??[]) as MedicalShift[]);if(!b.error)setLinks((b.data??[]) as MedicalLink[])},[supabase,user]);
 useEffect(()=>{void load()},[load]);
 const hours=useMemo(()=>hoursBetween(form.start_time,form.end_time),[form.start_time,form.end_time]);
 const base=brlInputToNumber(form.base_value||"0"),additional=brlInputToNumber(form.additional_value||"0"),total=base+additional,effectiveHour=hours>0?total/hours:0;
 const currentMonth=today.slice(0,7);
 const monthItems=items.filter(i=>i.shift_date?.slice(0,7)===currentMonth&&i.status!=="CANCELED");
 const worked=monthItems.filter(i=>["WORKED","BILLED","AWAITING","RECEIVED"].includes(i.status));
 const monthValue=worked.reduce((s,i)=>s+Number(i.total_value||0),0),monthHours=worked.reduce((s,i)=>s+Number(i.hours||0),0),pending=monthItems.filter(i=>["BILLED","AWAITING"].includes(i.status)).reduce((s,i)=>s+Number(i.total_value||0),0);

 async function save(e:React.FormEvent){e.preventDefault();if(!user||saving)return;setSaving(true);setError("");setMessage("");try{if(!form.hospital.trim())throw new Error("Informe o hospital ou local do plantão.");if(base<=0)throw new Error("Informe um valor base válido para o plantão.");const {error}=await supabase.from('medical_shifts').insert({...form,user_id:user.id,professional_link_id:form.professional_link_id||null,hospital:form.hospital.trim(),hours,base_value:base,additional_value:additional,total_value:total,expected_payment_date:form.expected_payment_date||null});if(error)throw error;setOpen(false);setForm({...form,hospital:"",base_value:"",additional_value:"",expected_payment_date:"",notes:""});setMessage("Plantão salvo. Ele já entrou na agenda profissional.");await load()}catch(err){setError(err instanceof Error?err.message:"Não foi possível salvar o plantão.")}finally{setSaving(false)}}
 async function setStatus(i:MedicalShift,status:string){if(!user)return;setError("");setMessage("");const now=new Date().toISOString();const {error}=await supabase.from('medical_shifts').update({status,updated_at:now}).eq('id',i.id);if(error){setError(error.message);return}if(status==='AWAITING'){const {data:exists}=await supabase.from('medical_receivables').select('id').eq('source_type','SHIFT').eq('source_id',i.id).maybeSingle();if(!exists)await supabase.from('medical_receivables').insert({user_id:user.id,source_type:'SHIFT',source_id:i.id,service_date:i.shift_date,source_name:i.hospital,description:`Plantão ${i.start_time.slice(0,5)}–${i.end_time.slice(0,5)}`,amount:Number(i.total_value),expected_payment_date:i.expected_payment_date,status:'PENDING'})}if(status==='RECEIVED'){const {data:r}=await supabase.from('medical_receivables').select('id,status').eq('source_type','SHIFT').eq('source_id',i.id).maybeSingle();if(r)await supabase.from('medical_receivables').update({status:'RECEIVED',received_at:now,updated_at:now}).eq('id',r.id);const {data:t}=await supabase.from('medical_professional_transactions').select('id').eq('source_type','SHIFT').eq('source_id',i.id).maybeSingle();if(!t)await supabase.from('medical_professional_transactions').insert({user_id:user.id,transaction_date:today,kind:'INCOME',category:'Plantões',amount:Number(i.total_value),description:i.hospital,source_type:'SHIFT',source_id:i.id})}setMessage(status==='WORKED'?"Plantão marcado como trabalhado.":status==='AWAITING'?"Plantão enviado para A Receber.":status==='RECEIVED'?"Recebimento confirmado e lançado no financeiro.":"Status atualizado.");await load()}

 return <MedicalAppShell><div className="space-y-7"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#0f4c81]">Tempo → trabalho → receita</p><h1 className="mt-2 text-3xl font-black md:text-4xl">Plantões</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Registre uma vez e acompanhe horas, valor efetivo da hora, situação do trabalho e recebimento.</p></div><Button onClick={()=>setOpen(!open)} className="bg-[#0f4c81]"><Plus className="size-4"/>Registrar plantão</Button></div>
 {error&&<div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}{message&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">{message}</div>}
 <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Plantões no mês" value={String(monthItems.length)} helper="Agendados e realizados"/><Metric label="Horas trabalhadas" value={`${monthHours.toFixed(1).replace('.',',')}h`} helper="Plantões já trabalhados"/><Metric label="Receita trabalhada" value={medicalCurrency.format(monthValue)} helper="Valor gerado pelo trabalho"/><Metric label="A receber" value={medicalCurrency.format(pending)} helper="Faturado ou aguardando pagamento" tone="amber"/></section>
 {open&&<form onSubmit={save} className="rounded-[1.75rem] bg-white p-5 shadow-sm md:p-6"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Field label="Vínculo"><Select value={form.professional_link_id} onChange={e=>{const link=links.find(x=>x.id===e.target.value);setForm({...form,professional_link_id:e.target.value,hospital:link?.name||form.hospital,base_value:link?.shift_value?String(Number(link.shift_value).toFixed(2)).replace('.',','):form.base_value})}}><option value="">Sem vínculo definido</option>{links.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</Select></Field><Field label="Hospital / local"><Input required placeholder="Hospital / local" value={form.hospital} onChange={e=>setForm({...form,hospital:e.target.value})}/></Field><Field label="Data do plantão"><Input type="date" required value={form.shift_date} onChange={e=>setForm({...form,shift_date:e.target.value})}/></Field><Field label="Horário"><div className="grid grid-cols-2 gap-2"><Input type="time" required value={form.start_time} onChange={e=>setForm({...form,start_time:e.target.value})}/><Input type="time" required value={form.end_time} onChange={e=>setForm({...form,end_time:e.target.value})}/></div></Field><Field label="Valor base"><MoneyInput value={form.base_value} onValueChange={v=>setForm({...form,base_value:v})} placeholder="R$ 0,00"/></Field><Field label="Adicional"><MoneyInput value={form.additional_value} onValueChange={v=>setForm({...form,additional_value:v})} placeholder="R$ 0,00"/></Field><Field label="Previsão de pagamento"><Input type="date" value={form.expected_payment_date} onChange={e=>setForm({...form,expected_payment_date:e.target.value})}/></Field><div className="grid grid-cols-2 gap-2"><Small label="Carga horária" value={`${hours}h`}/><Small label="Hora efetiva" value={total>0?medicalCurrency.format(effectiveHour):'—'}/></div></div><div className="mt-5 flex items-center justify-between rounded-2xl bg-[#0f4c81]/5 p-4"><div><p className="text-xs text-slate-500">Valor total previsto</p><p className="mt-1 text-2xl font-black text-[#0f4c81]">{medicalCurrency.format(total)}</p></div><Button disabled={saving} className="bg-[#0f4c81]">{saving?"Salvando...":"Salvar plantão"}</Button></div></form>}
 <div className="grid gap-4 xl:grid-cols-3">{items.map(i=><article key={i.id} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex justify-between"><span className="grid size-11 place-items-center rounded-2xl bg-[#0f4c81]/10 text-[#0f4c81]"><CalendarDays className="size-5"/></span><button onClick={async()=>{if(confirm('Excluir plantão?')){const {error}=await supabase.from('medical_shifts').delete().eq('id',i.id);if(error)setError(error.message);else await load()}}}><Trash2 className="size-4 text-slate-400"/></button></div><h3 className="mt-5 font-black">{i.hospital}</h3><p className="mt-1 text-xs text-slate-500">{new Date(i.shift_date+'T12:00:00').toLocaleDateString('pt-BR')} · {i.start_time.slice(0,5)}–{i.end_time.slice(0,5)}</p><div className="mt-5 grid grid-cols-2 gap-3"><Small label="Valor total" value={medicalCurrency.format(Number(i.total_value))}/><Small label="Valor/hora" value={Number(i.hours)>0?medicalCurrency.format(Number(i.total_value)/Number(i.hours)):'—'}/></div><div className="mt-4 flex items-center justify-between"><p className="flex items-center gap-1 text-xs text-slate-500"><Clock3 className="size-3"/>{i.hours}h</p><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-black uppercase text-slate-600">{shiftStatus[i.status]||i.status}</span></div><div className="mt-5 flex flex-wrap gap-2">{i.status==='SCHEDULED'&&<Button size="sm" variant="outline" onClick={()=>void setStatus(i,'WORKED')}>Marcar trabalhado</Button>}{['WORKED','BILLED'].includes(i.status)&&<Button size="sm" variant="outline" onClick={()=>void setStatus(i,'AWAITING')}>Enviar para A Receber</Button>}{i.status==='AWAITING'&&<Button size="sm" className="bg-emerald-600 hover:bg-emerald-700" onClick={()=>void setStatus(i,'RECEIVED')}><CheckCircle2 className="size-4"/>Marcar recebido</Button>}</div></article>)}{!items.length&&!open&&<div className="col-span-full rounded-3xl border border-dashed border-slate-300 p-12 text-center text-sm text-slate-500">Nenhum plantão registrado. Cadastre um vínculo e registre seu primeiro plantão.</div>}</div></div></MedicalAppShell>}

function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="mb-2 block text-[10px] font-black uppercase tracking-wide text-slate-500">{label}</span>{children}</label>}
function Small({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-slate-50 p-3"><p className="text-[10px] font-black uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-sm font-black">{value}</p></div>}
function Metric({label,value,helper,tone='default'}:{label:string;value:string;helper:string;tone?:'default'|'amber'}){return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-[10px] font-black uppercase tracking-wide text-slate-400">{label}</p><p className={`mt-2 text-2xl font-black ${tone==='amber'?'text-amber-700':'text-slate-950'}`}>{value}</p><p className="mt-1 text-xs text-slate-500">{helper}</p></div>}
