"use client";
import {useCallback,useEffect,useMemo,useState,type FormEvent} from "react";
import {ChevronRight,Plus,ShoppingBag,Trash2,Wallet} from "lucide-react";
import {useAuth} from "@/context/AuthContext";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Input} from "@/components/ui/input";
import {Select} from "@/components/ui/select";
import {SidePanel} from "@/components/ui/side-panel";
import {currency} from "@/lib/finance";
import {getBankTheme} from "@/lib/bank-theme";

type Account={id:string;name:string;institution:string|null;current_balance:number};
type UserCard={id:string;nickname:string|null;brand:string|null;issuer:string|null;last_four:string|null;credit_limit:number;closing_day:number;due_day:number;payment_account_id:string|null;is_active:boolean};
type Invoice={id:string;card_id:string;reference_month:string;due_date:string|null;status:string;total_amount:number;paid_amount:number;payment_account_id?:string|null};
type Purchase={id:string;card_id:string;description:string;merchant:string|null;category:string|null;total_amount:number;installments:number;purchase_date:string};
type Installment={id:string;purchase_id:string;card_id:string;invoice_id:string|null;installment_number:number;installment_count:number;amount:number;due_month:string;status:string};
const money=(v:string)=>Number((v||"0").replace(/\./g,"").replace(",","."))||0;
const iso=(d:Date)=>d.toISOString().slice(0,10);
const monthStart=(d:Date)=>new Date(d.getFullYear(),d.getMonth(),1);
const addMonths=(d:Date,n:number)=>new Date(d.getFullYear(),d.getMonth()+n,1);
const stamp=(i:Invoice)=>new Date(`${i.due_date||i.reference_month}T12:00:00`).getTime();
const sortInvoices=(items:Invoice[])=>[...items].sort((a,b)=>{const ap=a.status==="PAID",bp=b.status==="PAID";if(ap!==bp)return ap?1:-1;return ap?stamp(b)-stamp(a):stamp(a)-stamp(b)});
const statusPt=(s:string)=>s==="PAID"?"Paga":s==="OVERDUE"?"Vencida":s==="CLOSED"?"Fechada":"Em aberto";
const datePt=(d?:string|null)=>d?new Date(`${d}T12:00:00`).toLocaleDateString("pt-BR"):"—";
const monthPt=(d:string)=>new Date(`${d}T12:00:00`).toLocaleDateString("pt-BR",{month:"long",year:"numeric"});

export function CreditCardsManager(){
 const {supabase,user}=useAuth();
 const [cards,setCards]=useState<UserCard[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[invoices,setInvoices]=useState<Invoice[]>([]),[purchases,setPurchases]=useState<Purchase[]>([]),[installments,setInstallments]=useState<Installment[]>([]);
 const [open,setOpen]=useState(false),[purchaseOpen,setPurchaseOpen]=useState(false),[selectedCard,setSelectedCard]=useState<string|null>(null),[selectedInvoice,setSelectedInvoice]=useState<string|null>(null),[selectedPurchase,setSelectedPurchase]=useState<string|null>(null),[paying,setPaying]=useState<string|null>(null),[deletingPurchase,setDeletingPurchase]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const [form,setForm]=useState<Record<string,string>>({brand:"Mastercard"}),[purchase,setPurchase]=useState<Record<string,string>>({installments:"1",purchase_date:iso(new Date())}),[payment,setPayment]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{if(!user)return;const[c,a,i,p,ci]=await Promise.all([supabase.from("cards").select("*").order("created_at",{ascending:false}),supabase.from("financial_accounts").select("id,name,institution,current_balance").eq("is_active",true).order("name"),supabase.from("card_invoices").select("*").order("reference_month",{ascending:true}),supabase.from("card_purchases").select("*").order("purchase_date",{ascending:false}),supabase.from("card_installments").select("*").order("due_month",{ascending:true})]);if(c.error)setError(c.error.message);else setCards((c.data||[]) as UserCard[]);if(a.error)setError(a.error.message);else setAccounts((a.data||[]) as Account[]);if(i.error)setError(i.error.message);else setInvoices((i.data||[]) as Invoice[]);if(p.error)setError(p.error.message);else setPurchases((p.data||[]) as Purchase[]);if(ci.error)setError(ci.error.message);else setInstallments((ci.data||[]) as Installment[])},[supabase,user]);
 useEffect(()=>{void load()},[load]);
 const totals=useMemo(()=>{const limit=cards.reduce((s,c)=>s+Number(c.credit_limit||0),0),used=invoices.filter(i=>i.status!=="PAID").reduce((s,i)=>s+Number(i.total_amount||0)-Number(i.paid_amount||0),0);return{limit,used,available:Math.max(0,limit-used)}},[cards,invoices]);
 const activeCard=cards.find(c=>c.id===selectedCard)||null;
 const activeInvoice=invoices.find(i=>i.id===selectedInvoice)||null;
 const activePurchase=purchases.find(p=>p.id===selectedPurchase)||null;
 async function save(ev:FormEvent){ev.preventDefault();if(!user)return;setSaving(true);setError("");const limit=money(form.credit_limit);if(limit<=0){setError("Informe um limite válido.");setSaving(false);return}const {error:e}=await supabase.from("cards").insert({user_id:user.id,nickname:(form.nickname||"").trim(),brand:form.brand||"Outro",issuer:form.issuer?.trim()||null,last_four:form.last_four||"0000",credit_limit:limit,current_invoice:0,closing_day:Number(form.closing_day||1),due_day:Number(form.due_day||1),payment_account_id:form.payment_account_id||null,is_active:true});if(e)setError(e.message);else{setForm({brand:"Mastercard"});setOpen(false);await load()}setSaving(false)}
 async function removeCard(card:UserCard){if(!confirm(`Excluir ${card.nickname||"este cartão"}?`))return;const {error:e}=await supabase.from("cards").delete().eq("id",card.id);if(e)setError(e.message);else{setSelectedCard(null);await load()}}
 async function removePurchase(p:Purchase){if(deletingPurchase)return;if(!confirm(`Excluir apenas a compra “${p.description}” de ${currency.format(Number(p.total_amount))}? As parcelas serão removidas e as faturas serão recalculadas.`))return;setDeletingPurchase(true);setError("");const {error:e}=await supabase.rpc("equity_delete_financial_record",{p_kind:"CARD_PURCHASE",p_record_id:p.id});if(e)setError(e.message);else{setSelectedPurchase(null);await load()}setDeletingPurchase(false)}
 async function savePurchase(ev:FormEvent){ev.preventDefault();if(!user)return;const card=cards.find(c=>c.id===purchase.card_id),total=money(purchase.total_amount),count=Math.max(1,Number(purchase.installments||1));if(!card||total<=0){setError("Selecione cartão e valor válido.");return}setSaving(true);setError("");try{const {data:p,error:pe}=await supabase.from("card_purchases").insert({user_id:user.id,card_id:card.id,description:purchase.description,merchant:purchase.merchant||null,category:purchase.category||"Outros",total_amount:total,installments:count,purchase_date:purchase.purchase_date}).select("id").single();if(pe)throw pe;const base=Math.floor(total/count*100)/100,pd=new Date(`${purchase.purchase_date}T12:00:00`),first=new Date(pd.getFullYear(),pd.getMonth()+(pd.getDate()>card.closing_day?1:0),1);const working=[...invoices];for(let n=0;n<count;n++){const m=addMonths(first,n),ref=iso(monthStart(m));let inv=working.find(i=>i.card_id===card.id&&i.reference_month===ref);if(!inv){const due=new Date(m.getFullYear(),m.getMonth(),Math.min(card.due_day||1,28));const {data,error}=await supabase.from("card_invoices").insert({user_id:user.id,card_id:card.id,reference_month:ref,due_date:iso(due),status:"OPEN",total_amount:0,paid_amount:0,payment_account_id:card.payment_account_id||null}).select("*").single();if(error)throw error;inv=data as Invoice;working.push(inv)}const amount=n===count-1?Number((total-base*(count-1)).toFixed(2)):base;const {error:ie}=await supabase.from("card_installments").insert({user_id:user.id,purchase_id:p.id,card_id:card.id,invoice_id:inv.id,installment_number:n+1,installment_count:count,amount,due_month:ref,status:"OPEN"});if(ie)throw ie;const newTotal=Number(inv.total_amount||0)+amount;const {error:ue}=await supabase.from("card_invoices").update({total_amount:newTotal,updated_at:new Date().toISOString()}).eq("id",inv.id);if(ue)throw ue;inv.total_amount=newTotal}setPurchase({installments:"1",purchase_date:iso(new Date())});setPurchaseOpen(false);await load()}catch(e:any){setError(e?.message||"Falha ao registrar compra.")}finally{setSaving(false)}}
 async function payInvoice(inv:Invoice){if(!user||paying||inv.status==="PAID")return;const card=cards.find(c=>c.id===inv.card_id),accountId=payment[inv.id]||inv.payment_account_id||card?.payment_account_id||"",account=accounts.find(a=>a.id===accountId),due=Number(inv.total_amount)-Number(inv.paid_amount);if(!account){setError("Selecione a conta para pagamento.");return}setPaying(inv.id);setError("");try{const {data:latest,error:le}=await supabase.from("card_invoices").select("status,total_amount,paid_amount").eq("id",inv.id).single();if(le)throw le;if(latest.status==="PAID")throw new Error("Esta fatura já foi paga.");const amount=Number(latest.total_amount)-Number(latest.paid_amount);if(amount<=0)throw new Error("Não há valor pendente nesta fatura.");const now=new Date().toISOString();const {error:e}=await supabase.from("financial_account_entries").insert({user_id:user.id,account_id:account.id,entry_type:"CARD_INVOICE_PAYMENT",amount:-amount,description:`Pagamento de fatura ${card?.nickname||"cartão"}`,occurred_on:iso(new Date()),metadata:{invoice_id:inv.id}});if(e)throw e;const {error:b}=await supabase.from("financial_accounts").update({current_balance:Number(account.current_balance)-amount,updated_at:now}).eq("id",account.id);if(b)throw b;const {error:ii}=await supabase.from("card_invoices").update({status:"PAID",paid_amount:Number(latest.total_amount),paid_at:now,payment_account_id:account.id,updated_at:now}).eq("id",inv.id).neq("status","PAID");if(ii)throw ii;await supabase.from("card_installments").update({status:"PAID"}).eq("invoice_id",inv.id);await load()}catch(e:any){setError(e?.message||"Falha ao pagar fatura.")}finally{setPaying(null)}}
 return <div className="space-y-7">
  <section className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#9b772c]">Crédito e faturas</p><h1 className="mt-2 text-3xl font-black">Cartões e faturas</h1><p className="mt-2 text-sm text-slate-500">Clique em um cartão para abrir seus detalhes, faturas e compras.</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>setPurchaseOpen(v=>!v)}><ShoppingBag className="size-4"/>Nova compra</Button><Button onClick={()=>setOpen(v=>!v)}><Plus className="size-4"/>Novo cartão</Button></div></section>
  {error&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}
  <section className="grid gap-4 md:grid-cols-3"><Metric label="Limite total" value={totals.limit}/><Metric label="Em faturas" value={totals.used}/><Metric label="Disponível" value={totals.available}/></section>
  {open&&<Card><CardHeader><CardTitle>Novo cartão</CardTitle></CardHeader><CardContent><form onSubmit={save} className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Field label="Nome"><Input required value={form.nickname||""} onChange={e=>setForm({...form,nickname:e.target.value})}/></Field><Field label="Banco / emissor"><Input value={form.issuer||""} onChange={e=>setForm({...form,issuer:e.target.value})}/></Field><Field label="Bandeira"><Select value={form.brand||"Mastercard"} onChange={e=>setForm({...form,brand:e.target.value})}><option>Mastercard</option><option>Visa</option><option>Elo</option><option>Amex</option><option>Hipercard</option><option>Outro</option></Select></Field><Field label="Últimos 4"><Input required maxLength={4} value={form.last_four||""} onChange={e=>setForm({...form,last_four:e.target.value.replace(/\D/g,"")})}/></Field><Field label="Limite"><Input required value={form.credit_limit||""} onChange={e=>setForm({...form,credit_limit:e.target.value})}/></Field><Field label="Fechamento"><Input required type="number" min="1" max="31" value={form.closing_day||""} onChange={e=>setForm({...form,closing_day:e.target.value})}/></Field><Field label="Vencimento"><Input required type="number" min="1" max="31" value={form.due_day||""} onChange={e=>setForm({...form,due_day:e.target.value})}/></Field><Field label="Conta para pagamento"><Select value={form.payment_account_id||""} onChange={e=>setForm({...form,payment_account_id:e.target.value})}><option value="">Nenhuma</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.institution?`${a.institution} · `:""}{a.name}</option>)}</Select></Field><div className="xl:col-span-4 flex justify-end"><Button type="submit" disabled={saving}>Salvar cartão</Button></div></form></CardContent></Card>}
  {purchaseOpen&&<Card><CardHeader><CardTitle>Nova compra</CardTitle></CardHeader><CardContent><form onSubmit={savePurchase} className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Field label="Cartão"><Select required value={purchase.card_id||""} onChange={e=>setPurchase({...purchase,card_id:e.target.value})}><option value="">Selecione</option>{cards.map(c=><option key={c.id} value={c.id}>{c.nickname||"Cartão"}</option>)}</Select></Field><Field label="Descrição"><Input required value={purchase.description||""} onChange={e=>setPurchase({...purchase,description:e.target.value})}/></Field><Field label="Valor"><Input required value={purchase.total_amount||""} onChange={e=>setPurchase({...purchase,total_amount:e.target.value})}/></Field><Field label="Parcelas"><Input required type="number" min="1" max="48" value={purchase.installments||"1"} onChange={e=>setPurchase({...purchase,installments:e.target.value})}/></Field><Field label="Data"><Input required type="date" value={purchase.purchase_date||""} onChange={e=>setPurchase({...purchase,purchase_date:e.target.value})}/></Field><Field label="Estabelecimento"><Input value={purchase.merchant||""} onChange={e=>setPurchase({...purchase,merchant:e.target.value})}/></Field><Field label="Categoria"><Input value={purchase.category||""} onChange={e=>setPurchase({...purchase,category:e.target.value})}/></Field><div className="flex items-end"><Button type="submit" className="w-full" disabled={saving}>Gerar faturas</Button></div></form></CardContent></Card>}
  <section className="grid gap-5 lg:grid-cols-2">{cards.map(card=>{const theme=getBankTheme(card.issuer||card.nickname),list=sortInvoices(invoices.filter(i=>i.card_id===card.id)),used=list.filter(i=>i.status!=="PAID").reduce((s,i)=>s+Number(i.total_amount)-Number(i.paid_amount),0);return <button type="button" key={card.id} onClick={()=>setSelectedCard(card.id)} className="group overflow-hidden rounded-2xl bg-white text-left shadow-[0_12px_35px_rgba(15,23,42,.07)] transition duration-200 hover:-translate-y-1 hover:shadow-[0_18px_45px_rgba(15,23,42,.14)]"><div className="p-6" style={{backgroundColor:theme.bgColor,color:theme.fgColor}}><div className="flex justify-between"><b>{theme.initials}</b><span>•••• {card.last_four||"0000"}</span></div><h3 className="mt-5 text-xl font-black">{card.nickname||"Cartão sem nome"}</h3><p>{card.issuer||theme.label} · {card.brand||"Crédito"}</p><div className="mt-5 flex justify-between gap-5"><span>Em aberto <b>{currency.format(used)}</b></span><span>Disponível <b>{currency.format(Math.max(0,Number(card.credit_limit)-used))}</b></span></div></div><div className="flex items-center justify-between px-6 py-4 text-sm font-bold text-slate-600"><span>Ver detalhes, faturas e compras</span><ChevronRight className="size-4 transition group-hover:translate-x-1"/></div></button>})}</section>
  <SidePanel open={!!activeCard} onClose={()=>{setSelectedCard(null);setSelectedInvoice(null);setSelectedPurchase(null)}} title={activeCard?.nickname||"Cartão"} subtitle={activeCard?`${activeCard.issuer||"Emissor"} · ${activeCard.brand||"Crédito"} · •••• ${activeCard.last_four||"0000"}`:undefined} footer={activeCard?<div className="flex gap-2"><Button variant="outline" className="flex-1" onClick={()=>{setPurchase({...purchase,card_id:activeCard.id,installments:"1",purchase_date:iso(new Date())});setPurchaseOpen(true);setSelectedCard(null)}}><ShoppingBag className="size-4"/>Nova compra</Button><Button variant="outline" size="icon" onClick={()=>void removeCard(activeCard)}><Trash2 className="size-4"/></Button></div>:undefined}>
   {activeCard&&(()=>{const theme=getBankTheme(activeCard.issuer||activeCard.nickname),list=sortInvoices(invoices.filter(i=>i.card_id===activeCard.id)),used=list.filter(i=>i.status!=="PAID").reduce((s,i)=>s+Number(i.total_amount)-Number(i.paid_amount),0),available=Math.max(0,Number(activeCard.credit_limit)-used);return <div className="space-y-6"><div className="rounded-3xl p-6 text-white" style={{backgroundColor:theme.bgColor,color:theme.fgColor}}><p className="text-sm opacity-75">Limite total</p><p className="mt-1 text-3xl font-black">{currency.format(Number(activeCard.credit_limit))}</p><div className="mt-5 grid grid-cols-2 gap-4 text-sm"><div><p className="opacity-70">Em aberto</p><b>{currency.format(used)}</b></div><div><p className="opacity-70">Disponível</p><b>{currency.format(available)}</b></div><div><p className="opacity-70">Fecha dia</p><b>{activeCard.closing_day}</b></div><div><p className="opacity-70">Vence dia</p><b>{activeCard.due_day}</b></div></div></div><div><div className="mb-3 flex items-center justify-between"><h3 className="font-black">Faturas</h3><span className="text-xs text-slate-400">{list.length} registros</span></div><div className="overflow-hidden rounded-2xl border border-slate-200">{list.length===0?<p className="p-5 text-sm text-slate-500">Nenhuma fatura registrada.</p>:list.map(inv=>{const due=Number(inv.total_amount)-Number(inv.paid_amount);return <button type="button" key={inv.id} onClick={()=>setSelectedInvoice(inv.id)} className="flex w-full items-center justify-between gap-4 border-b border-slate-100 p-4 text-left transition last:border-0 hover:bg-slate-50"><div><b className="capitalize">{monthPt(inv.reference_month)}</b><p className="mt-1 text-xs text-slate-400">{statusPt(inv.status)} · vencimento {datePt(inv.due_date)}</p></div><div className="flex items-center gap-2"><b>{currency.format(due)}</b><ChevronRight className="size-4 text-slate-300"/></div></button>})}</div></div></div>})()}
  </SidePanel>
  <SidePanel open={!!activeInvoice} onClose={()=>{setSelectedInvoice(null);setSelectedPurchase(null)}} title={activeInvoice?`Fatura de ${monthPt(activeInvoice.reference_month)}`:"Fatura"} subtitle={activeInvoice?`${statusPt(activeInvoice.status)} · vence ${datePt(activeInvoice.due_date)}`:undefined} footer={activeInvoice&&activeInvoice.status!=="PAID"&&Number(activeInvoice.total_amount)-Number(activeInvoice.paid_amount)>0?<div className="flex gap-2"><Select value={payment[activeInvoice.id]||activeInvoice.payment_account_id||activeCard?.payment_account_id||""} onChange={e=>setPayment({...payment,[activeInvoice.id]:e.target.value})}><option value="">Conta para pagamento</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.institution?`${a.institution} · `:""}{a.name}</option>)}</Select><Button disabled={paying===activeInvoice.id} onClick={()=>void payInvoice(activeInvoice)}><Wallet className="size-4"/>{paying===activeInvoice.id?"Pagando...":"Pagar fatura"}</Button></div>:undefined}>
   {activeInvoice&&<div className="space-y-6"><div className="grid grid-cols-2 gap-3"><Mini label="Valor da fatura" value={currency.format(Number(activeInvoice.total_amount))}/><Mini label="Valor pago" value={currency.format(Number(activeInvoice.paid_amount))}/></div><div><div className="mb-3 flex items-center justify-between"><h3 className="font-black">Compras desta fatura</h3><span className="text-xs text-slate-400">{installments.filter(i=>i.invoice_id===activeInvoice.id).length} itens</span></div><div className="overflow-hidden rounded-2xl border border-slate-200">{installments.filter(i=>i.invoice_id===activeInvoice.id).length===0?<p className="p-5 text-sm text-slate-500">Nenhuma compra vinculada.</p>:installments.filter(i=>i.invoice_id===activeInvoice.id).map(inst=>{const p=purchases.find(x=>x.id===inst.purchase_id);return <button type="button" key={inst.id} onClick={()=>p&&setSelectedPurchase(p.id)} className="flex w-full items-center justify-between gap-4 border-b border-slate-100 p-4 text-left transition last:border-0 hover:bg-slate-50"><div><b>{p?.description||"Compra"}</b><p className="mt-1 text-xs text-slate-400">{p?.merchant||p?.category||"Sem estabelecimento"} · parcela {inst.installment_number}/{inst.installment_count}</p></div><div className="flex items-center gap-2"><b>{currency.format(Number(inst.amount))}</b><ChevronRight className="size-4 text-slate-300"/></div></button>})}</div></div></div>}
  </SidePanel>
  <SidePanel open={!!activePurchase} onClose={()=>setSelectedPurchase(null)} title={activePurchase?.description||"Compra"} subtitle={activePurchase?.merchant||activePurchase?.category||"Detalhes da compra"} className="max-w-[440px]" footer={activePurchase?<div className="flex gap-2"><Button variant="outline" className="flex-1" onClick={()=>setSelectedPurchase(null)}>Fechar</Button><Button type="button" className="flex-1 bg-rose-600 text-white hover:bg-rose-700" disabled={deletingPurchase} onClick={()=>void removePurchase(activePurchase)}><Trash2 className="size-4"/>{deletingPurchase?"Excluindo...":"Excluir compra"}</Button></div>:undefined}>
   {activePurchase&&<div className="space-y-5"><div className="rounded-3xl bg-slate-950 p-6 text-white"><p className="text-sm text-slate-400">Valor total</p><p className="mt-1 text-3xl font-black">{currency.format(Number(activePurchase.total_amount))}</p></div><div className="grid grid-cols-2 gap-3"><Mini label="Data" value={datePt(activePurchase.purchase_date)}/><Mini label="Parcelas" value={String(activePurchase.installments)}/><Mini label="Categoria" value={activePurchase.category||"Outros"}/><Mini label="Estabelecimento" value={activePurchase.merchant||"—"}/></div><div><h3 className="mb-3 font-black">Parcelamento</h3><div className="overflow-hidden rounded-2xl border border-slate-200">{installments.filter(i=>i.purchase_id===activePurchase.id).map(inst=><div key={inst.id} className="flex items-center justify-between border-b border-slate-100 p-4 last:border-0"><span className="text-sm">Parcela {inst.installment_number}/{inst.installment_count}</span><b>{currency.format(Number(inst.amount))}</b></div>)}</div></div><div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">Ao excluir a compra, todas as parcelas vinculadas serão removidas e as faturas correspondentes serão recalculadas automaticamente.</div></div>}
  </SidePanel>
 </div>
}
function Metric({label,value}:{label:string;value:number}){return <Card className="border-0"><CardContent className="p-6"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-black">{currency.format(value)}</p></CardContent></Card>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-sm font-black text-slate-900">{value}</p></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="mb-1.5 block text-xs font-black uppercase text-slate-500">{label}</span>{children}</label>}
