"use client";
import {useCallback,useEffect,useMemo,useState,type FormEvent} from "react";
import {CreditCard,Plus,ShoppingBag,Wallet} from "lucide-react";
import {useAuth} from "@/context/AuthContext";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Input} from "@/components/ui/input";
import {Select} from "@/components/ui/select";
import {currency} from "@/lib/finance";
import {getBankTheme} from "@/lib/bank-theme";

type Account={id:string;name:string;institution:string|null;current_balance:number};
type UserCard={id:string;nickname:string;brand:string;issuer:string|null;last_four:string;credit_limit:number;current_invoice:number;closing_day:number;due_day:number;payment_account_id:string|null;is_active:boolean};
type Invoice={id:string;card_id:string;reference_month:string;due_date:string|null;status:string;total_amount:number;paid_amount:number;payment_account_id?:string|null};
const money=(v:string)=>Number((v||"0").replace(/\./g,"").replace(",","."))||0;
const iso=(d:Date)=>d.toISOString().slice(0,10);
const monthStart=(d:Date)=>new Date(d.getFullYear(),d.getMonth(),1);
const addMonths=(d:Date,n:number)=>new Date(d.getFullYear(),d.getMonth()+n,1);

export function CreditCardsManager(){
 const {supabase,user}=useAuth();
 const [cards,setCards]=useState<UserCard[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[invoices,setInvoices]=useState<Invoice[]>([]);
 const [open,setOpen]=useState(false),[purchaseOpen,setPurchaseOpen]=useState(false),[selected,setSelected]=useState<string|null>(null),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const [form,setForm]=useState<Record<string,string>>({brand:"Mastercard"}),[purchase,setPurchase]=useState<Record<string,string>>({installments:"1",purchase_date:iso(new Date())}),[payment,setPayment]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{if(!user)return;const[c,a,i]=await Promise.all([supabase.from("cards").select("*").order("created_at",{ascending:false}),supabase.from("financial_accounts").select("id,name,institution,current_balance").eq("is_active",true).order("name"),supabase.from("card_invoices").select("*").order("reference_month",{ascending:false})]);if(c.error)setError(c.error.message);else setCards((c.data??[]) as UserCard[]);if(a.error)setError(a.error.message);else setAccounts((a.data??[]) as Account[]);if(i.error)setError(i.error.message);else setInvoices((i.data??[]) as Invoice[])},[supabase,user]);
 useEffect(()=>{void load()},[load]);
 const totals=useMemo(()=>{const limit=cards.reduce((s,c)=>s+Number(c.credit_limit||0),0),used=invoices.filter(i=>i.status!=="PAID").reduce((s,i)=>s+Number(i.total_amount||0)-Number(i.paid_amount||0),0);return{limit,used,available:Math.max(0,limit-used)}},[cards,invoices]);
 async function save(ev:FormEvent){ev.preventDefault();if(!user)return;setSaving(true);setError("");const limit=money(form.credit_limit);if(limit<=0){setError("Informe um limite válido.");setSaving(false);return}const {error:e}=await supabase.from("cards").insert({user_id:user.id,nickname:form.nickname.trim(),brand:form.brand||"Outro",issuer:form.issuer?.trim()||null,last_four:form.last_four,credit_limit:limit,current_invoice:0,closing_day:Number(form.closing_day),due_day:Number(form.due_day),payment_account_id:form.payment_account_id||null,is_active:true});if(e)setError(e.message);else{setForm({brand:"Mastercard"});setOpen(false);await load()}setSaving(false)}
 async function savePurchase(ev:FormEvent){ev.preventDefault();if(!user)return;const card=cards.find(c=>c.id===purchase.card_id),total=money(purchase.total_amount),count=Math.max(1,Number(purchase.installments||1));if(!card||total<=0){setError("Selecione cartão e valor válido.");return}setSaving(true);setError("");try{const {data:p,error:pe}=await supabase.from("card_purchases").insert({user_id:user.id,card_id:card.id,description:purchase.description,merchant:purchase.merchant||null,category:purchase.category||"Outros",total_amount:total,installments:count,purchase_date:purchase.purchase_date}).select("id").single();if(pe)throw pe;const base=Math.floor(total/count*100)/100;const purchaseDate=new Date(`${purchase.purchase_date}T12:00:00`);const first=new Date(purchaseDate.getFullYear(),purchaseDate.getMonth()+(purchaseDate.getDate()>card.closing_day?1:0),1);for(let n=0;n<count;n++){const m=addMonths(first,n),ref=iso(monthStart(m));let inv=invoices.find(i=>i.card_id===card.id&&i.reference_month===ref);if(!inv){const due=new Date(m.getFullYear(),m.getMonth(),Math.min(card.due_day,28));const {data,error}=await supabase.from("card_invoices").insert({user_id:user.id,card_id:card.id,reference_month:ref,due_date:iso(due),status:"OPEN",total_amount:0,paid_amount:0,payment_account_id:card.payment_account_id||null}).select("*").single();if(error)throw error;inv=data as Invoice;invoices.push(inv)}const amount=n===count-1?Number((total-base*(count-1)).toFixed(2)):base;const {error:ie}=await supabase.from("card_installments").insert({user_id:user.id,purchase_id:p.id,card_id:card.id,invoice_id:inv.id,installment_number:n+1,installment_count:count,amount,due_month:ref,status:"OPEN"});if(ie)throw ie;const newTotal=Number(inv.total_amount||0)+amount;const {error:ue}=await supabase.from("card_invoices").update({total_amount:newTotal,updated_at:new Date().toISOString()}).eq("id",inv.id);if(ue)throw ue;inv.total_amount=newTotal}setPurchase({installments:"1",purchase_date:iso(new Date())});setPurchaseOpen(false);await load()}catch(e:any){setError(e?.message||"Falha ao registrar compra.")}finally{setSaving(false)}}
 async function payInvoice(inv:Invoice){if(!user)return;const card=cards.find(c=>c.id===inv.card_id),accountId=payment[inv.id]||inv.payment_account_id||card?.payment_account_id||"",account=accounts.find(a=>a.id===accountId),due=Number(inv.total_amount)-Number(inv.paid_amount);if(!account){setError("Selecione a conta para pagamento.");return}setSaving(true);setError("");const now=new Date().toISOString();const {error:e1}=await supabase.from("financial_account_entries").insert({user_id:user.id,account_id:account.id,entry_type:"CARD_INVOICE_PAYMENT",amount:-due,description:`Pagamento de fatura ${card?.nickname||"cartão"}`,occurred_on:iso(new Date()),metadata:{invoice_id:inv.id}});if(e1){setError(e1.message);setSaving(false);return}await supabase.from("financial_accounts").update({current_balance:Number(account.current_balance)-due,updated_at:now}).eq("id",account.id);await supabase.from("card_invoices").update({status:"PAID",paid_amount:Number(inv.total_amount),paid_at:now,payment_account_id:account.id,updated_at:now}).eq("id",inv.id);await supabase.from("card_installments").update({status:"PAID"}).eq("invoice_id",inv.id);setSaving(false);await load()}
 return <div className="space-y-7">
  <section className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#9b772c]">Crédito e faturas</p><h1 className="mt-2 text-3xl font-black">Cartões e faturas</h1><p className="mt-2 text-sm text-slate-500">Limite, compras, parcelas e pagamento conectado às contas.</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>setPurchaseOpen(v=>!v)}><ShoppingBag className="size-4"/>Nova compra</Button><Button onClick={()=>setOpen(v=>!v)}><Plus className="size-4"/>Novo cartão</Button></div></section>
  {error&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}
  <section className="grid gap-4 md:grid-cols-3"><Metric label="Limite total" value={totals.limit}/><Metric label="Em faturas" value={totals.used}/><Metric label="Disponível" value={totals.available}/></section>
  {open&&<Card><CardHeader><CardTitle>Novo cartão</CardTitle></CardHeader><CardContent><form onSubmit={save} className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Field label="Nome"><Input required value={form.nickname||""} onChange={e=>setForm({...form,nickname:e.target.value})}/></Field><Field label="Banco / emissor"><Input value={form.issuer||""} onChange={e=>setForm({...form,issuer:e.target.value})}/></Field><Field label="Bandeira"><Select value={form.brand||"Mastercard"} onChange={e=>setForm({...form,brand:e.target.value})}><option>Mastercard</option><option>Visa</option><option>Elo</option><option>Amex</option><option>Hipercard</option><option>Outro</option></Select></Field><Field label="Últimos 4"><Input required maxLength={4} pattern="[0-9]{4}" value={form.last_four||""} onChange={e=>setForm({...form,last_four:e.target.value.replace(/\D/g,"")})}/></Field><Field label="Limite"><Input required value={form.credit_limit||""} onChange={e=>setForm({...form,credit_limit:e.target.value})}/></Field><Field label="Fechamento"><Input required type="number" min="1" max="31" value={form.closing_day||""} onChange={e=>setForm({...form,closing_day:e.target.value})}/></Field><Field label="Vencimento"><Input required type="number" min="1" max="31" value={form.due_day||""} onChange={e=>setForm({...form,due_day:e.target.value})}/></Field><Field label="Conta para pagamento"><Select value={form.payment_account_id||""} onChange={e=>setForm({...form,payment_account_id:e.target.value})}><option value="">Nenhuma</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.institution?`${a.institution} · `:""}{a.name}</option>)}</Select></Field><div className="xl:col-span-4 flex justify-end"><Button type="submit" disabled={saving}>{saving?"Salvando...":"Salvar cartão"}</Button></div></form></CardContent></Card>}
  {purchaseOpen&&<Card><CardHeader><CardTitle>Nova compra</CardTitle></CardHeader><CardContent><form onSubmit={savePurchase} className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Field label="Cartão"><Select required value={purchase.card_id||""} onChange={e=>setPurchase({...purchase,card_id:e.target.value})}><option value="">Selecione</option>{cards.map(c=><option key={c.id} value={c.id}>{c.nickname}</option>)}</Select></Field><Field label="Descrição"><Input required value={purchase.description||""} onChange={e=>setPurchase({...purchase,description:e.target.value})}/></Field><Field label="Valor"><Input required value={purchase.total_amount||""} onChange={e=>setPurchase({...purchase,total_amount:e.target.value})}/></Field><Field label="Parcelas"><Input required type="number" min="1" max="48" value={purchase.installments||"1"} onChange={e=>setPurchase({...purchase,installments:e.target.value})}/></Field><Field label="Data"><Input required type="date" value={purchase.purchase_date||""} onChange={e=>setPurchase({...purchase,purchase_date:e.target.value})}/></Field><Field label="Estabelecimento"><Input value={purchase.merchant||""} onChange={e=>setPurchase({...purchase,merchant:e.target.value})}/></Field><Field label="Categoria"><Input value={purchase.category||""} onChange={e=>setPurchase({...purchase,category:e.target.value})}/></Field><div className="flex items-end"><Button type="submit" className="w-full" disabled={saving}>{saving?"Processando...":"Gerar faturas"}</Button></div></form></CardContent></Card>}
  <section className="grid gap-5 lg:grid-cols-2">{cards.map(card=>{const theme=getBankTheme(card.issuer||card.nickname),list=invoices.filter(i=>i.card_id===card.id),used=list.filter(i=>i.status!=="PAID").reduce((s,i)=>s+Number(i.total_amount)-Number(i.paid_amount),0);return <Card key={card.id} className="overflow-hidden border-0"><div className={`p-6 ${theme.card}`}><div className="flex justify-between"><span className="grid size-12 place-items-center rounded-2xl bg-white/20 font-black">{theme.initials}</span><span>•••• {card.last_four}</span></div><h3 className="mt-5 text-xl font-black">{card.nickname}</h3><p className="opacity-80">{card.issuer||theme.label} · {card.brand}</p><div className="mt-5 flex justify-between"><span>Em aberto <b>{currency.format(used)}</b></span><span>Disponível <b>{currency.format(Math.max(0,Number(card.credit_limit)-used))}</b></span></div></div><CardContent className="p-6"><Button variant="outline" className="w-full" onClick={()=>setSelected(selected===card.id?null:card.id)}>Ver faturas</Button>{selected===card.id&&<div className="mt-4 space-y-3">{list.length===0?<p className="text-sm text-slate-500">Nenhuma fatura.</p>:list.map(inv=>{const due=Number(inv.total_amount)-Number(inv.paid_amount),accountId=payment[inv.id]||inv.payment_account_id||card.payment_account_id||"",acc=accounts.find(a=>a.id===accountId),t=getBankTheme(acc?.institution||acc?.name);return <div key={inv.id} className="rounded-xl border p-3"><div className="flex justify-between"><div><b>{new Date(`${inv.reference_month}T12:00:00`).toLocaleDateString("pt-BR",{month:"long",year:"numeric"})}</b><p className="text-xs text-slate-400">{inv.status}</p></div><b>{currency.format(due)}</b></div>{inv.status!=="PAID"&&due>0&&<div className="mt-3 flex gap-2"><Select className={accountId?`${t.soft} ${t.text} font-bold`:""} value={accountId} onChange={e=>setPayment({...payment,[inv.id]:e.target.value})}><option value="">Conta para pagamento</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.institution?`${a.institution} · `:""}{a.name}</option>)}</Select><Button type="button" disabled={saving} onClick={()=>void payInvoice(inv)}><Wallet className="size-4"/>Pagar</Button></div>}</div>})}</div>}</CardContent></Card>})}</section>
 </div>
}
function Metric({label,value}:{label:string;value:number}){return <Card className="border-0"><CardContent className="p-6"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-black">{currency.format(value)}</p></CardContent></Card>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="mb-1.5 block text-xs font-black uppercase text-slate-500">{label}</span>{children}</label>}
