"use client";
import {useCallback,useEffect,useMemo,useState,type FormEvent} from "react";
import {ArrowLeftRight,Landmark,Plus,WalletCards} from "lucide-react";
import {useAuth} from "@/context/AuthContext";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Input} from "@/components/ui/input";
import {Select} from "@/components/ui/select";
import {currency} from "@/lib/finance";
import {getBankTheme} from "@/lib/bank-theme";

const accountTypes:Record<string,string>={CHECKING:"Conta corrente",SAVINGS:"Poupança",WALLET:"Carteira digital",CASH:"Dinheiro",INVESTMENT:"Investimentos",PAYMENT:"Conta de pagamento",OTHER:"Outra"};
type Account={id:string;name:string;institution:string|null;account_type:string;opening_balance:number;current_balance:number;is_active:boolean;include_in_total:boolean};
type Entry={id:string;account_id:string;entry_type:string;amount:number;description:string;occurred_on:string;created_at:string};
const toNumber=(v:string)=>Number((v||"0").replace(/\./g,"").replace(",","."))||0;

export function FinancialAccountsManager(){
 const {supabase,user}=useAuth();
 const [accounts,setAccounts]=useState<Account[]>([]),[entries,setEntries]=useState<Entry[]>([]),[open,setOpen]=useState(false),[transferOpen,setTransferOpen]=useState(false),[adjustOpen,setAdjustOpen]=useState<string|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const [form,setForm]=useState<Record<string,string>>({account_type:"CHECKING"}),[transfer,setTransfer]=useState<Record<string,string>>({}),[adjust,setAdjust]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{if(!user)return;setLoading(true);setError("");const[a,e]=await Promise.all([supabase.from("financial_accounts").select("*").order("created_at",{ascending:true}),supabase.from("financial_account_entries").select("*").order("occurred_on",{ascending:false}).order("created_at",{ascending:false}).limit(50)]);if(a.error)setError(a.error.message);else setAccounts((a.data??[]) as Account[]);if(e.error)setError(e.error.message);else setEntries((e.data??[]) as Entry[]);setLoading(false)},[supabase,user]);
 useEffect(()=>{void load()},[load]);
 const total=useMemo(()=>accounts.filter(a=>a.is_active&&a.include_in_total).reduce((s,a)=>s+Number(a.current_balance||0),0),[accounts]);
 async function createAccount(ev:FormEvent){ev.preventDefault();if(!user)return;setSaving(true);setError("");const opening=toNumber(form.opening_balance);const {data,error:e}=await supabase.from("financial_accounts").insert({user_id:user.id,name:form.name.trim(),institution:form.institution?.trim()||null,account_type:form.account_type||"CHECKING",opening_balance:opening,current_balance:opening,is_active:true,include_in_total:true}).select("id").single();if(e){setError(e.message);setSaving(false);return}if(opening!==0){const {error:ee}=await supabase.from("financial_account_entries").insert({user_id:user.id,account_id:data.id,entry_type:"OPENING",amount:opening,description:"Saldo inicial",occurred_on:new Date().toISOString().slice(0,10)});if(ee){setError(ee.message);setSaving(false);return}}setForm({account_type:"CHECKING"});setOpen(false);setSaving(false);await load()}
 async function saveAdjustment(ev:FormEvent){ev.preventDefault();if(!user||!adjustOpen)return;const account=accounts.find(a=>a.id===adjustOpen),amount=toNumber(adjust.amount)*(adjust.direction==="OUT"?-1:1);if(!account||!amount)return;setSaving(true);const {error:e1}=await supabase.from("financial_account_entries").insert({user_id:user.id,account_id:account.id,entry_type:"ADJUSTMENT",amount,description:adjust.description||"Ajuste de saldo",occurred_on:new Date().toISOString().slice(0,10)});if(e1){setError(e1.message);setSaving(false);return}const {error:e2}=await supabase.from("financial_accounts").update({current_balance:Number(account.current_balance)+amount,updated_at:new Date().toISOString()}).eq("id",account.id);if(e2)setError(e2.message);else{setAdjust({});setAdjustOpen(null);await load()}setSaving(false)}
 async function saveTransfer(ev:FormEvent){ev.preventDefault();if(!user)return;const from=accounts.find(a=>a.id===transfer.from),to=accounts.find(a=>a.id===transfer.to),amount=toNumber(transfer.amount);if(!from||!to||from.id===to.id||amount<=0){setError("Selecione contas diferentes e um valor válido.");return}setSaving(true);setError("");const date=transfer.date||new Date().toISOString().slice(0,10),description=transfer.description||"Transferência entre contas";const {data:t,error:e0}=await supabase.from("account_transfers").insert({user_id:user.id,from_account_id:from.id,to_account_id:to.id,amount,occurred_on:date,description}).select("id").single();if(e0){setError(e0.message);setSaving(false);return}const {error:e1}=await supabase.from("financial_account_entries").insert([{user_id:user.id,account_id:from.id,entry_type:"TRANSFER_OUT",amount:-amount,description,occurred_on:date,metadata:{transfer_id:t.id}},{user_id:user.id,account_id:to.id,entry_type:"TRANSFER_IN",amount,description,occurred_on:date,metadata:{transfer_id:t.id}}]);if(e1){setError(e1.message);setSaving(false);return}await Promise.all([supabase.from("financial_accounts").update({current_balance:Number(from.current_balance)-amount,updated_at:new Date().toISOString()}).eq("id",from.id),supabase.from("financial_accounts").update({current_balance:Number(to.current_balance)+amount,updated_at:new Date().toISOString()}).eq("id",to.id)]);setTransfer({});setTransferOpen(false);setSaving(false);await load()}
 const fromTheme=getBankTheme(accounts.find(a=>a.id===transfer.from)?.institution||accounts.find(a=>a.id===transfer.from)?.name),toTheme=getBankTheme(accounts.find(a=>a.id===transfer.to)?.institution||accounts.find(a=>a.id===transfer.to)?.name);
 return <div className="space-y-7">
  <section className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#9b772c]">Fundação financeira</p><h1 className="mt-2 text-3xl font-black">Contas financeiras</h1><p className="mt-2 text-sm text-slate-500">Saldos reais por banco, carteira e conta.</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>setTransferOpen(v=>!v)}><ArrowLeftRight className="size-4"/>Transferir</Button><Button onClick={()=>setOpen(v=>!v)}><Plus className="size-4"/>Nova conta</Button></div></section>
  {error&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}
  <section className="grid gap-4 md:grid-cols-3"><Metric label="Saldo total das contas" value={loading?"—":currency.format(total)}/><Metric label="Contas ativas" value={String(accounts.filter(a=>a.is_active).length)}/><Metric label="Movimentações recentes" value={String(entries.length)}/></section>
  {open&&<Card><CardHeader><CardTitle>Adicionar conta financeira</CardTitle></CardHeader><CardContent><form onSubmit={createAccount} className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Field label="Nome"><Input required value={form.name||""} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ex.: Conta principal"/></Field><Field label="Instituição"><Input value={form.institution||""} onChange={e=>setForm({...form,institution:e.target.value})} placeholder="Itaú, Nubank, Santander..."/></Field><Field label="Tipo"><Select value={form.account_type||"CHECKING"} onChange={e=>setForm({...form,account_type:e.target.value})}>{Object.entries(accountTypes).map(([k,v])=><option key={k} value={k}>{v}</option>)}</Select></Field><Field label="Saldo atual / inicial"><Input inputMode="decimal" value={form.opening_balance||""} onChange={e=>setForm({...form,opening_balance:e.target.value})}/></Field><div className="xl:col-span-4 flex justify-end"><Button type="submit" disabled={saving}>{saving?"Salvando...":"Salvar conta"}</Button></div></form></CardContent></Card>}
  {transferOpen&&<Card><CardHeader><CardTitle>Transferência entre contas</CardTitle></CardHeader><CardContent><form onSubmit={saveTransfer} className="grid gap-4 md:grid-cols-2 xl:grid-cols-5"><Field label="Origem"><Select className={transfer.from?`${fromTheme.soft} ${fromTheme.text} font-bold`:""} required value={transfer.from||""} onChange={e=>setTransfer({...transfer,from:e.target.value})}><option value="">Selecione</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.institution?`${a.institution} · `:""}{a.name}</option>)}</Select></Field><Field label="Destino"><Select className={transfer.to?`${toTheme.soft} ${toTheme.text} font-bold`:""} required value={transfer.to||""} onChange={e=>setTransfer({...transfer,to:e.target.value})}><option value="">Selecione</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.institution?`${a.institution} · `:""}{a.name}</option>)}</Select></Field><Field label="Valor"><Input required value={transfer.amount||""} onChange={e=>setTransfer({...transfer,amount:e.target.value})}/></Field><Field label="Data"><Input type="date" value={transfer.date||new Date().toISOString().slice(0,10)} onChange={e=>setTransfer({...transfer,date:e.target.value})}/></Field><Field label="Descrição"><Input value={transfer.description||""} onChange={e=>setTransfer({...transfer,description:e.target.value})}/></Field><div className="xl:col-span-5 flex justify-end"><Button type="submit" disabled={saving}>Confirmar transferência</Button></div></form></CardContent></Card>}
  <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{accounts.map(a=>{const theme=getBankTheme(a.institution||a.name);return <Card key={a.id} className="overflow-hidden border-0 shadow-[0_12px_35px_rgba(15,23,42,.08)]"><div className={`p-5 ${theme.card}`}><div className="flex items-center justify-between"><span className="grid size-12 place-items-center rounded-2xl bg-white/20 text-sm font-black">{theme.initials}</span><span className="rounded-full bg-white/20 px-2.5 py-1 text-xs font-black">{a.is_active?"Ativa":"Inativa"}</span></div><h3 className="mt-5 text-xl font-black">{a.name}</h3><p className="text-sm opacity-80">{a.institution||accountTypes[a.account_type]}</p><p className="mt-5 text-3xl font-black">{currency.format(Number(a.current_balance||0))}</p><p className="mt-1 text-xs opacity-70">Saldo inicial: {currency.format(Number(a.opening_balance||0))}</p></div><CardContent className="p-5"><Button variant="outline" className="w-full" onClick={()=>setAdjustOpen(adjustOpen===a.id?null:a.id)}>Ajustar saldo</Button>{adjustOpen===a.id&&<form onSubmit={saveAdjustment} className="mt-4 space-y-3"><Select value={adjust.direction||"IN"} onChange={e=>setAdjust({...adjust,direction:e.target.value})}><option value="IN">Adicionar ao saldo</option><option value="OUT">Retirar do saldo</option></Select><Input required placeholder="Valor" value={adjust.amount||""} onChange={e=>setAdjust({...adjust,amount:e.target.value})}/><Input placeholder="Motivo" value={adjust.description||""} onChange={e=>setAdjust({...adjust,description:e.target.value})}/><Button type="submit" disabled={saving} className="w-full">Salvar ajuste</Button></form>}</CardContent></Card>})}</section>
  {accounts.length===0&&!loading&&<Card className="border-0"><CardContent className="grid min-h-64 place-items-center text-center"><div><WalletCards className="mx-auto size-10 text-slate-300"/><h3 className="mt-4 font-black">Nenhuma conta financeira cadastrada</h3><p className="mt-2 text-sm text-slate-500">Cadastre sua primeira conta para começar.</p></div></CardContent></Card>}
  {entries.length>0&&<Card className="border-0"><CardHeader><CardTitle>Últimas movimentações</CardTitle></CardHeader><CardContent className="divide-y">{entries.slice(0,12).map(e=>{const acc=accounts.find(a=>a.id===e.account_id),theme=getBankTheme(acc?.institution||acc?.name);return <div key={e.id} className="flex items-center justify-between py-3"><div className="flex items-center gap-3"><span className={`grid size-9 place-items-center rounded-xl text-xs font-black ${theme.soft} ${theme.text}`}>{theme.initials}</span><div><p className="text-sm font-bold">{e.description}</p><p className="text-xs text-slate-400">{acc?.name||"Conta"} · {e.occurred_on.split("-").reverse().join("/")}</p></div></div><b className={Number(e.amount)>=0?"text-emerald-700":"text-rose-700"}>{Number(e.amount)>=0?"+":""}{currency.format(Number(e.amount))}</b></div>})}</CardContent></Card>}
 </div>
}
function Metric({label,value}:{label:string;value:string}){return <Card className="border-0"><CardContent className="p-6"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></CardContent></Card>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="mb-1.5 block text-xs font-black uppercase text-slate-500">{label}</span>{children}</label>}
