"use client";
import {useCallback,useEffect,useMemo,useState,type FormEvent} from "react";
import {ArrowLeftRight,ChevronRight,Plus,Trash2,WalletCards} from "lucide-react";
import {useAuth} from "@/context/AuthContext";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Input} from "@/components/ui/input";
import {Select} from "@/components/ui/select";
import {SidePanel} from "@/components/ui/side-panel";
import {currency} from "@/lib/finance";
import {getBankTheme} from "@/lib/bank-theme";

const accountTypes:Record<string,string>={CHECKING:"Conta corrente",SAVINGS:"Poupança",WALLET:"Carteira digital",CASH:"Dinheiro",INVESTMENT:"Investimentos",PAYMENT:"Conta de pagamento",OTHER:"Outra"};
type Account={id:string;name:string;institution:string|null;account_type:string;opening_balance:number;current_balance:number;is_active:boolean;include_in_total:boolean};
type Entry={id:string;account_id:string;entry_type:string;amount:number;description:string;occurred_on:string;created_at:string};
const toNumber=(v:string)=>Number((v||"0").replace(/\./g,"").replace(",","."))||0;

export function FinancialAccountsManager(){
 const {supabase,user}=useAuth();
 const [accounts,setAccounts]=useState<Account[]>([]),[entries,setEntries]=useState<Entry[]>([]),[open,setOpen]=useState(false),[transferOpen,setTransferOpen]=useState(false),[adjustOpen,setAdjustOpen]=useState<string|null>(null),[selectedAccount,setSelectedAccount]=useState<string|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const [form,setForm]=useState<Record<string,string>>({account_type:"CHECKING"}),[transfer,setTransfer]=useState<Record<string,string>>({}),[adjust,setAdjust]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{if(!user)return;setLoading(true);setError("");const[a,e]=await Promise.all([supabase.from("financial_accounts").select("*").order("created_at",{ascending:true}),supabase.from("financial_account_entries").select("*").order("occurred_on",{ascending:false}).order("created_at",{ascending:false}).limit(100)]);if(a.error)setError(a.error.message);else setAccounts((a.data??[]) as Account[]);if(e.error)setError(e.error.message);else setEntries((e.data??[]) as Entry[]);setLoading(false)},[supabase,user]);
 useEffect(()=>{void load()},[load]);
 const total=useMemo(()=>accounts.filter(a=>a.is_active&&a.include_in_total).reduce((s,a)=>s+Number(a.current_balance||0),0),[accounts]);
 const selected=accounts.find(a=>a.id===selectedAccount)||null;
 const selectedEntries=selected?entries.filter(e=>e.account_id===selected.id):[];
 async function createAccount(ev:FormEvent){ev.preventDefault();if(!user)return;setSaving(true);setError("");const name=(form.name||"").trim();if(!name){setError("Informe o nome da conta.");setSaving(false);return}const opening=toNumber(form.opening_balance);const {data,error:e}=await supabase.from("financial_accounts").insert({user_id:user.id,name,institution:form.institution?.trim()||null,account_type:form.account_type||"CHECKING",opening_balance:opening,current_balance:opening,is_active:true,include_in_total:true}).select("id").single();if(e){setError(e.message);setSaving(false);return}if(opening!==0){const {error:ee}=await supabase.from("financial_account_entries").insert({user_id:user.id,account_id:data.id,entry_type:"OPENING",amount:opening,description:"Saldo inicial",occurred_on:new Date().toISOString().slice(0,10)});if(ee){setError(ee.message);setSaving(false);return}}setForm({account_type:"CHECKING"});setOpen(false);setSaving(false);await load()}
 async function removeAccount(a:Account){if(!window.confirm(`Excluir a conta ${a.name}?`))return;const hasEntries=entries.some(e=>e.account_id===a.id);if(hasEntries){setError("Essa conta possui movimentações. Zere/ajuste o histórico antes de excluir.");return}const {error:e}=await supabase.from("financial_accounts").delete().eq("id",a.id);if(e)setError(e.message);else{setSelectedAccount(null);await load()}}
 async function saveAdjustment(ev:FormEvent){ev.preventDefault();if(!user||!adjustOpen)return;const account=accounts.find(a=>a.id===adjustOpen),amount=toNumber(adjust.amount)*(adjust.direction==="OUT"?-1:1);if(!account||!amount)return;setSaving(true);const {error:e1}=await supabase.from("financial_account_entries").insert({user_id:user.id,account_id:account.id,entry_type:"ADJUSTMENT",amount,description:adjust.description||"Ajuste de saldo",occurred_on:new Date().toISOString().slice(0,10)});if(e1){setError(e1.message);setSaving(false);return}const {error:e2}=await supabase.from("financial_accounts").update({current_balance:Number(account.current_balance)+amount,updated_at:new Date().toISOString()}).eq("id",account.id);if(e2)setError(e2.message);else{setAdjust({});setAdjustOpen(null);await load()}setSaving(false)}
 async function saveTransfer(ev:FormEvent){ev.preventDefault();if(!user)return;const from=accounts.find(a=>a.id===transfer.from),to=accounts.find(a=>a.id===transfer.to),amount=toNumber(transfer.amount);if(!from||!to||from.id===to.id||amount<=0){setError("Selecione contas diferentes e um valor válido.");return}setSaving(true);setError("");const date=transfer.date||new Date().toISOString().slice(0,10),description=transfer.description||"Transferência entre contas";const {data:t,error:e0}=await supabase.from("account_transfers").insert({user_id:user.id,from_account_id:from.id,to_account_id:to.id,amount,occurred_on:date,description}).select("id").single();if(e0){setError(e0.message);setSaving(false);return}const {error:e1}=await supabase.from("financial_account_entries").insert([{user_id:user.id,account_id:from.id,entry_type:"TRANSFER_OUT",amount:-amount,description,occurred_on:date,metadata:{transfer_id:t.id}},{user_id:user.id,account_id:to.id,entry_type:"TRANSFER_IN",amount,description,occurred_on:date,metadata:{transfer_id:t.id}}]);if(e1){setError(e1.message);setSaving(false);return}await Promise.all([supabase.from("financial_accounts").update({current_balance:Number(from.current_balance)-amount,updated_at:new Date().toISOString()}).eq("id",from.id),supabase.from("financial_accounts").update({current_balance:Number(to.current_balance)+amount,updated_at:new Date().toISOString()}).eq("id",to.id)]);setTransfer({});setTransferOpen(false);setSaving(false);await load()}
 return <div className="space-y-7">
  <section className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#9b772c]">Fundação financeira</p><h1 className="mt-2 text-3xl font-black">Contas financeiras</h1><p className="mt-2 text-sm text-slate-500">Clique em uma conta para abrir todos os detalhes sem sair da tela.</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>setTransferOpen(v=>!v)}><ArrowLeftRight className="size-4"/>Transferir</Button><Button onClick={()=>setOpen(v=>!v)}><Plus className="size-4"/>Nova conta</Button></div></section>
  {error&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}
  <section className="grid gap-4 md:grid-cols-3"><Metric label="Saldo total das contas" value={loading?"—":currency.format(total)}/><Metric label="Contas ativas" value={String(accounts.filter(a=>a.is_active).length)}/><Metric label="Movimentações recentes" value={String(entries.length)}/></section>
  {open&&<Card><CardHeader><CardTitle>Adicionar conta financeira</CardTitle></CardHeader><CardContent><form onSubmit={createAccount} className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Field label="Nome"><Input required value={form.name||""} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ex.: Conta principal"/></Field><Field label="Instituição"><Input value={form.institution||""} onChange={e=>setForm({...form,institution:e.target.value})} placeholder="Itaú, Nubank, Santander..."/></Field><Field label="Tipo"><Select value={form.account_type||"CHECKING"} onChange={e=>setForm({...form,account_type:e.target.value})}>{Object.entries(accountTypes).map(([k,v])=><option key={k} value={k}>{v}</option>)}</Select></Field><Field label="Saldo atual / inicial"><Input inputMode="decimal" value={form.opening_balance||""} onChange={e=>setForm({...form,opening_balance:e.target.value})}/></Field><div className="xl:col-span-4 flex justify-end"><Button type="submit" disabled={saving}>{saving?"Salvando...":"Salvar conta"}</Button></div></form></CardContent></Card>}
  {transferOpen&&<Card><CardHeader><CardTitle>Transferência entre contas</CardTitle></CardHeader><CardContent><form onSubmit={saveTransfer} className="grid gap-4 md:grid-cols-2 xl:grid-cols-5"><Field label="Origem"><Select required value={transfer.from||""} onChange={e=>setTransfer({...transfer,from:e.target.value})}><option value="">Selecione</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.institution?`${a.institution} · `:""}{a.name}</option>)}</Select></Field><Field label="Destino"><Select required value={transfer.to||""} onChange={e=>setTransfer({...transfer,to:e.target.value})}><option value="">Selecione</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.institution?`${a.institution} · `:""}{a.name}</option>)}</Select></Field><Field label="Valor"><Input required value={transfer.amount||""} onChange={e=>setTransfer({...transfer,amount:e.target.value})}/></Field><Field label="Data"><Input type="date" value={transfer.date||new Date().toISOString().slice(0,10)} onChange={e=>setTransfer({...transfer,date:e.target.value})}/></Field><Field label="Descrição"><Input value={transfer.description||""} onChange={e=>setTransfer({...transfer,description:e.target.value})}/></Field><div className="xl:col-span-5 flex justify-end"><Button type="submit" disabled={saving}>Confirmar transferência</Button></div></form></CardContent></Card>}
  <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{accounts.map(a=>{const theme=getBankTheme(a.institution||a.name);return <button key={a.id} type="button" onClick={()=>setSelectedAccount(a.id)} className="group overflow-hidden rounded-2xl bg-white text-left shadow-[0_12px_35px_rgba(15,23,42,.08)] transition duration-200 hover:-translate-y-1 hover:shadow-[0_20px_45px_rgba(15,23,42,.14)] focus:outline-none focus:ring-2 focus:ring-[#d2aa51]/50"><div className="p-5" style={{backgroundColor:theme.bgColor,color:theme.fgColor}}><div className="flex items-center justify-between"><span className="grid size-12 place-items-center rounded-2xl text-sm font-black" style={{backgroundColor:"rgba(255,255,255,.18)"}}>{theme.initials}</span><span className="rounded-full px-2.5 py-1 text-xs font-black" style={{backgroundColor:"rgba(255,255,255,.18)"}}>{a.is_active?"Ativa":"Inativa"}</span></div><h3 className="mt-5 text-xl font-black">{a.name||"Conta sem nome"}</h3><p className="text-sm" style={{opacity:.82}}>{a.institution||accountTypes[a.account_type]||"Instituição financeira"}</p><p className="mt-5 text-3xl font-black">{currency.format(Number(a.current_balance||0))}</p><p className="mt-1 text-xs" style={{opacity:.72}}>Saldo inicial: {currency.format(Number(a.opening_balance||0))}</p></div><div className="flex items-center justify-between p-5 text-sm font-bold text-slate-500"><span>Ver detalhes e movimentações</span><ChevronRight className="size-4 transition-transform group-hover:translate-x-1"/></div></button>})}</section>
  {accounts.length===0&&!loading&&<Card className="border-0"><CardContent className="grid min-h-64 place-items-center text-center"><div><WalletCards className="mx-auto size-10 text-slate-300"/><h3 className="mt-4 font-black">Nenhuma conta financeira cadastrada</h3></div></CardContent></Card>}
  {entries.length>0&&<Card className="border-0"><CardHeader><CardTitle>Últimas movimentações</CardTitle></CardHeader><CardContent className="divide-y">{entries.slice(0,12).map(e=>{const acc=accounts.find(a=>a.id===e.account_id),theme=getBankTheme(acc?.institution||acc?.name);return <button type="button" onClick={()=>acc&&setSelectedAccount(acc.id)} key={e.id} className="flex w-full items-center justify-between py-3 text-left transition hover:bg-slate-50"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl text-xs font-black" style={{backgroundColor:theme.softColor,color:theme.textColor}}>{theme.initials}</span><div><p className="text-sm font-bold">{e.description}</p><p className="text-xs text-slate-400">{acc?.name||"Conta"} · {e.occurred_on.split("-").reverse().join("/")}</p></div></div><b className={Number(e.amount)>=0?"text-emerald-700":"text-rose-700"}>{Number(e.amount)>=0?"+":""}{currency.format(Number(e.amount))}</b></button>})}</CardContent></Card>}
  <SidePanel open={Boolean(selected)} onClose={()=>{setSelectedAccount(null);setAdjustOpen(null)}} title={selected?.name||"Conta financeira"} subtitle={selected?.institution||accountTypes[selected?.account_type||""]} footer={selected&&<div className="flex gap-2"><Button variant="outline" className="flex-1" onClick={()=>setAdjustOpen(adjustOpen===selected.id?null:selected.id)}>Ajustar saldo</Button><Button variant="outline" size="icon" onClick={()=>void removeAccount(selected)} aria-label="Excluir conta"><Trash2 className="size-4"/></Button></div>}>
   {selected&&<div className="space-y-6"><div className="rounded-2xl p-5" style={{backgroundColor:getBankTheme(selected.institution||selected.name).bgColor,color:getBankTheme(selected.institution||selected.name).fgColor}}><p className="text-sm opacity-75">Saldo atual</p><p className="mt-2 text-4xl font-black">{currency.format(Number(selected.current_balance||0))}</p><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><div><p className="opacity-70">Saldo inicial</p><b>{currency.format(Number(selected.opening_balance||0))}</b></div><div><p className="opacity-70">Tipo</p><b>{accountTypes[selected.account_type]||"Outra"}</b></div></div></div>
    {adjustOpen===selected.id&&<form onSubmit={saveAdjustment} className="space-y-3 rounded-2xl border border-[#d2aa51]/20 bg-[#d2aa51]/5 p-4"><p className="font-black">Ajustar saldo</p><Select value={adjust.direction||"IN"} onChange={e=>setAdjust({...adjust,direction:e.target.value})}><option value="IN">Adicionar ao saldo</option><option value="OUT">Retirar do saldo</option></Select><Input required placeholder="Valor" value={adjust.amount||""} onChange={e=>setAdjust({...adjust,amount:e.target.value})}/><Input placeholder="Motivo" value={adjust.description||""} onChange={e=>setAdjust({...adjust,description:e.target.value})}/><Button type="submit" disabled={saving} className="w-full">Salvar ajuste</Button></form>}
    <div><div className="mb-3 flex items-center justify-between"><h3 className="font-black">Movimentações</h3><span className="text-xs font-bold text-slate-400">{selectedEntries.length} registros</span></div>{selectedEntries.length===0?<div className="rounded-2xl bg-slate-50 p-5 text-sm text-slate-500">Nenhuma movimentação registrada nesta conta.</div>:<div className="divide-y rounded-2xl border border-slate-100">{selectedEntries.slice(0,25).map(e=><div key={e.id} className="flex items-center justify-between p-4"><div><p className="text-sm font-bold text-slate-900">{e.description}</p><p className="mt-1 text-xs text-slate-400">{e.occurred_on.split("-").reverse().join("/")}</p></div><b className={Number(e.amount)>=0?"text-emerald-700":"text-rose-700"}>{Number(e.amount)>=0?"+":""}{currency.format(Number(e.amount))}</b></div>)}</div>}</div>
   </div>}
  </SidePanel>
 </div>
}
function Metric({label,value}:{label:string;value:string}){return <Card className="border-0 transition duration-200 hover:-translate-y-0.5 hover:shadow-md"><CardContent className="p-6"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></CardContent></Card>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="mb-1.5 block text-xs font-black uppercase text-slate-500">{label}</span>{children}</label>}
