"use client";

import {useCallback,useEffect,useMemo,useState,type FormEvent} from "react";
import {ArrowDownLeft,ArrowUpRight,Copy,Edit3,Filter,Plus,ReceiptText,RotateCcw,Search,Trash2,X} from "lucide-react";
import {useAuth} from "@/context/AuthContext";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Input} from "@/components/ui/input";
import {MoneyInput,brlInputToNumber} from "@/components/ui/money-input";
import {Select} from "@/components/ui/select";
import {Textarea} from "@/components/ui/textarea";
import {SidePanel} from "@/components/ui/side-panel";
import {EmptyState} from "./EmptyState";
import {currency,dateBR,type Transaction,type TransactionType} from "@/lib/finance";
import {cn} from "@/lib/utils";
import {CategoryMultiSelect} from "./CategoryMultiSelect";
import {SmartFinancialInput} from "@/components/ai/SmartFinancialInput";
import {categoryGroups} from "@/lib/transaction-categories";

type FinancialAccount={id:string;name:string;institution:string|null;current_balance:number};
type ExtendedTransaction=Transaction&{account_id?:string|null;payment_method?:string|null;categories?:string[]|null;notes?:string|null;created_at?:string};
type UserCategory={id:string;name:string;type:"INCOME"|"EXPENSE";product:string;archived:boolean};

const paymentPt:Record<string,string>={PIX:"PIX",DEBIT:"Débito",CASH:"Dinheiro",TRANSFER:"Transferência",BOLETO:"Boleto",OTHER:"Outro"};
const initialForm={description:"",amount:"",type:"EXPENSE" as TransactionType,categories:[] as string[],cost_center:"",occurred_on:new Date().toISOString().slice(0,10),notes:"",account_id:"",payment_method:"PIX"};
const moneyText=(value:number)=>Number(value||0).toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2});
const currentPeriod=()=>new Date().toISOString().slice(0,7);
function periodRange(period:string){const [year,month]=period.split("-").map(Number);const end=new Date(year,month,0).getDate();return{start:`${period}-01`,end:`${period}-${String(end).padStart(2,"0")}`}}
function dateForPeriod(period:string){const today=new Date().toISOString().slice(0,10);return today.startsWith(period)?today:`${period}-01`}

export function TransactionsManagerV522({institutional=false,compact=false}:{institutional?:boolean;compact?:boolean}){
 const {supabase,user}=useAuth();
 const [items,setItems]=useState<ExtendedTransaction[]>([]),[accounts,setAccounts]=useState<FinancialAccount[]>([]),[customCategories,setCustomCategories]=useState<UserCategory[]>([]);
 const [form,setForm]=useState(initialForm),[open,setOpen]=useState(false),[selected,setSelected]=useState<ExtendedTransaction|null>(null),[editing,setEditing]=useState(false),[editForm,setEditForm]=useState(initialForm);
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[deleting,setDeleting]=useState(false),[duplicating,setDuplicating]=useState(false),[error,setError]=useState("");
 const [period,setPeriod]=useState(currentPeriod()),[search,setSearch]=useState(""),[typeFilter,setTypeFilter]=useState("ALL"),[accountFilter,setAccountFilter]=useState("ALL"),[categoryFilter,setCategoryFilter]=useState("ALL");
 const product=institutional?"BUSINESS":"PERSONAL";

 useEffect(()=>{if(typeof window==="undefined"||compact)return;const q=new URLSearchParams(window.location.search);const m=q.get("mes"),t=q.get("tipo"),a=q.get("conta"),c=q.get("categoria");if(m&&/^\d{4}-\d{2}$/.test(m))setPeriod(m);if(t)setTypeFilter(t);if(a)setAccountFilter(a);if(c)setCategoryFilter(c)},[compact]);
 useEffect(()=>{if(typeof window==="undefined"||compact)return;const q=new URLSearchParams(window.location.search);q.set("mes",period);typeFilter==="ALL"?q.delete("tipo"):q.set("tipo",typeFilter);accountFilter==="ALL"?q.delete("conta"):q.set("conta",accountFilter);categoryFilter==="ALL"?q.delete("categoria"):q.set("categoria",categoryFilter);window.history.replaceState(null,"",`${window.location.pathname}?${q.toString()}`)},[period,typeFilter,accountFilter,categoryFilter,compact]);

 const load=useCallback(async()=>{if(!user)return;setLoading(true);setError("");const range=periodRange(period);let tq=supabase.from("transactions").select("*").order("occurred_on",{ascending:false}).order("created_at",{ascending:false});if(compact)tq=tq.limit(6);else tq=tq.gte("occurred_on",range.start).lte("occurred_on",range.end).limit(500);const [tr,ar,cr]=await Promise.all([tq,supabase.from("financial_accounts").select("id,name,institution,current_balance").eq("is_active",true).order("name"),supabase.from("user_categories").select("id,name,type,product,archived").eq("product",product).order("name")]);if(tr.error)setError(tr.error.message);else setItems((tr.data??[]) as ExtendedTransaction[]);if(!ar.error)setAccounts((ar.data??[]) as FinancialAccount[]);if(!cr.error)setCustomCategories((cr.data??[]) as UserCategory[]);setLoading(false)},[compact,period,product,supabase,user]);
 useEffect(()=>{void load()},[load]);

 const categoryOptions=useMemo(()=>{const set=new Set<string>();(["INCOME","EXPENSE"] as TransactionType[]).forEach(t=>categoryGroups(institutional,t).forEach(g=>g.items.forEach(x=>set.add(x))));customCategories.filter(x=>!x.archived).forEach(x=>set.add(x.name));items.forEach(x=>(x.categories?.length?x.categories:[x.category]).filter(Boolean).forEach(x=>set.add(x)));return [...set].sort((a,b)=>a.localeCompare(b,"pt-BR"))},[customCategories,institutional,items]);
 const customForType=(type:TransactionType)=>customCategories.filter(x=>!x.archived&&x.type===type).map(x=>x.name);

 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return items.filter(item=>{if(typeFilter!=="ALL"&&item.type!==typeFilter)return false;if(accountFilter!=="ALL"&&(item.account_id||"")!==accountFilter)return false;const cats=item.categories?.length?item.categories:[item.category];if(categoryFilter!=="ALL"&&!cats.includes(categoryFilter))return false;if(q&&!([item.description,item.category,...cats,item.cost_center??"",accounts.find(a=>a.id===item.account_id)?.name??"",item.notes??""].join(" ").toLowerCase().includes(q)))return false;return true})},[items,search,typeFilter,accountFilter,categoryFilter,accounts]);
 const totals=useMemo(()=>filtered.reduce((acc,x)=>{if(x.type==="INCOME")acc.income+=Number(x.amount);else acc.expense+=Number(x.amount);return acc},{income:0,expense:0}),[filtered]);

 async function persistCustom(names:string[],type:TransactionType){if(!user)return;const built=new Set(categoryGroups(institutional,type).flatMap(g=>g.items).map(x=>x.toLowerCase()));const existing=new Set(customCategories.filter(x=>x.type===type).map(x=>x.name.toLowerCase()));for(const name of names){if(built.has(name.toLowerCase())||existing.has(name.toLowerCase()))continue;const {error:e}=await supabase.from("user_categories").insert({user_id:user.id,product,type,name:name.trim(),archived:false});if(!e||e.code==="23505")existing.add(name.toLowerCase())}}

 async function save(event:FormEvent){event.preventDefault();if(!user)return;const amount=brlInputToNumber(form.amount);if(amount<=0)return setError("Informe um valor válido.");setSaving(true);setError("");const categories=form.categories.length?form.categories:["Outros"];const {error:e}=await supabase.rpc("equity_create_transaction",{p_description:form.description.trim(),p_amount:amount,p_type:form.type,p_categories:categories,p_cost_center:institutional?form.cost_center.trim():"",p_occurred_on:form.occurred_on,p_notes:form.notes.trim(),p_account_id:form.account_id||null,p_payment_method:form.payment_method||null});if(e)setError(e.message);else{await persistCustom(categories,form.type);setForm({...initialForm,occurred_on:dateForPeriod(period)});setOpen(false);await load()}setSaving(false)}

 function openItem(item:ExtendedTransaction){setSelected(item);setEditing(false);setEditForm({description:item.description,amount:moneyText(Number(item.amount)),type:item.type,categories:item.categories?.length?item.categories:[item.category||"Outros"],cost_center:item.cost_center||"",occurred_on:item.occurred_on,notes:item.notes||"",account_id:item.account_id||"",payment_method:item.payment_method||"PIX"})}
 async function updateItem(event:FormEvent){event.preventDefault();if(!selected)return;const amount=brlInputToNumber(editForm.amount);if(amount<=0)return setError("Informe um valor válido.");setSaving(true);setError("");const categories=editForm.categories.length?editForm.categories:["Outros"];const {error:e}=await supabase.rpc("equity_update_transaction",{p_transaction_id:selected.id,p_description:editForm.description.trim(),p_amount:amount,p_type:editForm.type,p_categories:categories,p_cost_center:institutional?editForm.cost_center.trim():"",p_occurred_on:editForm.occurred_on,p_notes:editForm.notes.trim(),p_account_id:editForm.account_id||null,p_payment_method:editForm.payment_method||null});if(e)setError(e.message);else{await persistCustom(categories,editForm.type);setSelected(null);setEditing(false);await load()}setSaving(false)}
 async function duplicate(item:ExtendedTransaction){if(duplicating)return;if(!window.confirm(`Duplicar “${item.description}” com o mesmo valor, conta e data?`))return;setDuplicating(true);setError("");const {error:e}=await supabase.rpc("equity_duplicate_transaction",{p_transaction_id:item.id,p_occurred_on:item.occurred_on});if(e)setError(e.message);else{setSelected(null);await load()}setDuplicating(false)}
 async function remove(item:ExtendedTransaction){if(deleting)return;if(!window.confirm(`Excluir apenas este registro de ${currency.format(Number(item.amount))}? O efeito financeiro será desfeito automaticamente.`))return;setDeleting(true);setError("");const {error:e}=await supabase.rpc("equity_delete_financial_record",{p_kind:"TRANSACTION",p_record_id:item.id});if(e)setError(e.message);else{setSelected(null);await load()}setDeleting(false)}
 function clearFilters(){setSearch("");setTypeFilter("ALL");setAccountFilter("ALL");setCategoryFilter("ALL")}
 const hasFilters=Boolean(search||typeFilter!=="ALL"||accountFilter!=="ALL"||categoryFilter!=="ALL");
 const selectedAccount=selected?accounts.find(a=>a.id===selected.account_id):null;

 return <>
  <Card className="border-0 shadow-[0_12px_35px_rgba(15,23,42,.07)]">
   <CardHeader className="gap-4 border-b border-slate-100 md:flex-row md:items-center md:justify-between"><div><CardTitle>{compact?"Últimos lançamentos":"Lançamentos financeiros"}</CardTitle><p className="mt-2 text-sm text-slate-500">Filtre, abra, edite, duplique ou exclua cada registro sem perder a coerência dos saldos.</p></div><Button onClick={()=>{setForm({...initialForm,occurred_on:dateForPeriod(period)});setOpen(v=>!v)}}>{open?<X className="size-4"/>:<Plus className="size-4"/>}{open?"Fechar":"Novo lançamento"}</Button></CardHeader>
   <CardContent className="p-6">
    {!compact&&<div className="mb-7"><SmartFinancialInput product={product} institutional={institutional} onSaved={load}/></div>}
    {error&&<div className="mb-5 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}
    {open&&<TransactionForm form={form} setForm={setForm} institutional={institutional} accounts={accounts} customItems={customForType(form.type)} saving={saving} onSubmit={save} title="Novo lançamento"/>}

    {!compact&&<div className="mb-5 space-y-3 rounded-2xl border border-slate-200 bg-slate-50/60 p-4"><div className="flex items-center gap-2"><Filter className="size-4 text-[#9a762b]"/><p className="text-sm font-black text-slate-800">Filtros</p>{hasFilters&&<button type="button" onClick={clearFilters} className="ml-auto flex items-center gap-1 text-xs font-bold text-slate-500 hover:text-slate-900"><RotateCcw className="size-3.5"/>Limpar</button>}</div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><label><Label>Mês</Label><Input type="month" value={period} onChange={e=>setPeriod(e.target.value||currentPeriod())}/></label><label><Label>Tipo</Label><Select value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}><option value="ALL">Receitas e despesas</option><option value="INCOME">Receitas</option><option value="EXPENSE">Despesas</option></Select></label><label><Label>Conta</Label><Select value={accountFilter} onChange={e=>setAccountFilter(e.target.value)}><option value="ALL">Todas as contas</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</Select></label><label><Label>Categoria</Label><Select value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}><option value="ALL">Todas as categorias</option>{categoryOptions.map(x=><option key={x}>{x}</option>)}</Select></label><label><Label>Buscar</Label><div className="flex items-center rounded-md border border-slate-200 bg-white px-3"><Search className="size-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Descrição..." className="h-10 w-full bg-transparent px-2 text-sm outline-none"/></div></label></div></div>}

    {!compact&&<div className="mb-5 grid gap-3 sm:grid-cols-3"><Mini label="Receitas filtradas" value={totals.income} tone="green"/><Mini label="Despesas filtradas" value={totals.expense} tone="red"/><Mini label="Resultado" value={totals.income-totals.expense} tone={totals.income-totals.expense>=0?"gold":"red"}/></div>}

    {loading?<div className="py-16 text-center text-sm text-slate-500">Carregando lançamentos...</div>:filtered.length===0?<EmptyState icon={ReceiptText} title="Nenhum lançamento encontrado" description={hasFilters?"Ajuste os filtros para ampliar a busca.":"Clique em “Novo lançamento” para registrar sua primeira receita ou despesa."}/>:<div className="overflow-x-auto"><table className="w-full min-w-[900px]"><thead><tr className="border-b border-slate-200 text-left text-xs uppercase tracking-wider text-slate-400"><th className="pb-3">Lançamento</th><th className="pb-3">Categoria</th><th className="pb-3">Conta</th>{institutional&&<th className="pb-3">Centro de custo</th>}<th className="pb-3">Data</th><th className="pb-3 text-right">Valor</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(item=>{const income=item.type==="INCOME",account=accounts.find(a=>a.id===item.account_id),cats=item.categories?.length?item.categories:[item.category];return <tr key={item.id} onClick={()=>openItem(item)} className="cursor-pointer transition hover:bg-slate-50"><td className="py-4"><div className="flex items-center gap-3"><span className={cn("grid size-10 place-items-center rounded-xl",income?"bg-emerald-50 text-emerald-700":"bg-rose-50 text-rose-700")}>{income?<ArrowUpRight className="size-4"/>:<ArrowDownLeft className="size-4"/>}</span><div><p className="text-sm font-bold text-slate-900">{item.description}</p>{item.payment_method&&<p className="text-xs text-slate-400">{paymentPt[item.payment_method]||"Outro"}</p>}</div></div></td><td className="py-4"><div className="flex max-w-xs flex-wrap gap-1">{cats.map((c,i)=><span key={`${item.id}-${c}`} className={cn("rounded-full px-2.5 py-1 text-xs font-bold",i===0?"bg-[#d2aa51]/10 text-[#8b6926]":"bg-slate-100 text-slate-600")}>{c}</span>)}</div></td><td className="py-4 text-sm text-slate-600">{account?.name||"—"}</td>{institutional&&<td className="py-4 text-sm text-slate-600">{item.cost_center||"—"}</td>}<td className="py-4 text-sm text-slate-500">{dateBR.format(new Date(`${item.occurred_on}T12:00:00`))}</td><td className={cn("py-4 text-right text-sm font-black",income?"text-emerald-700":"text-rose-700")}>{income?"+":"-"} {currency.format(Number(item.amount))}</td></tr>})}</tbody></table></div>}
   </CardContent>
  </Card>

  <SidePanel open={!!selected} onClose={()=>{setSelected(null);setEditing(false)}} title={selected?.description||"Lançamento"} subtitle={editing?"Editando lançamento":selected?.type==="INCOME"?"Receita":"Despesa"} footer={selected&&!editing?<div className="grid w-full grid-cols-3 gap-2"><Button variant="outline" onClick={()=>setEditing(true)}><Edit3 className="size-4"/>Editar</Button><Button variant="outline" disabled={duplicating} onClick={()=>void duplicate(selected)}><Copy className="size-4"/>{duplicating?"Duplicando...":"Duplicar"}</Button><Button className="bg-rose-600 text-white hover:bg-rose-700" disabled={deleting} onClick={()=>void remove(selected)}><Trash2 className="size-4"/>{deleting?"Excluindo...":"Excluir"}</Button></div>:undefined}>
   {selected&&(editing?<TransactionForm form={editForm} setForm={setEditForm} institutional={institutional} accounts={accounts} customItems={customForType(editForm.type)} saving={saving} onSubmit={updateItem} title="Editar lançamento" onCancel={()=>setEditing(false)}/>:<div className="space-y-4"><div className={cn("rounded-3xl p-6 text-white",selected.type==="INCOME"?"bg-emerald-600":"bg-rose-600")}><p className="text-sm opacity-80">Valor</p><p className="mt-2 text-4xl font-black">{selected.type==="INCOME"?"+":"-"} {currency.format(Number(selected.amount))}</p></div><Detail label="Data" value={dateBR.format(new Date(`${selected.occurred_on}T12:00:00`))}/><Detail label="Conta" value={selectedAccount?`${selectedAccount.institution?selectedAccount.institution+" · ":""}${selectedAccount.name}`:"Sem conta vinculada"}/><Detail label="Forma de pagamento" value={selected.payment_method?paymentPt[selected.payment_method]||"Outro":"Não informada"}/><Detail label="Categoria principal" value={selected.category||"Outros"}/>{(selected.categories?.length||0)>1&&<Detail label="Categorias associadas" value={(selected.categories||[]).slice(1).join(", ")}/>} {institutional&&<Detail label="Centro de custo" value={selected.cost_center||"Não informado"}/>} {selected.notes&&<Detail label="Observação" value={selected.notes}/>}<div className="rounded-2xl border border-[#d2aa51]/20 bg-[#d2aa51]/5 p-4 text-sm text-[#77591f]">Editar valor, tipo ou conta recalcula automaticamente os saldos envolvidos.</div></div>)}
  </SidePanel>
 </>;
}

function TransactionForm({form,setForm,institutional,accounts,customItems,saving,onSubmit,title,onCancel}:{form:typeof initialForm;setForm:(v:typeof initialForm)=>void;institutional:boolean;accounts:FinancialAccount[];customItems:string[];saving:boolean;onSubmit:(e:FormEvent)=>void;title:string;onCancel?:()=>void}){return <form onSubmit={onSubmit} className="mb-2 grid gap-4 rounded-2xl border border-[#d2aa51]/20 bg-[#d2aa51]/5 p-5 md:grid-cols-2"><div className="md:col-span-2 flex items-center justify-between"><p className="font-black text-slate-900">{title}</p>{onCancel&&<button type="button" onClick={onCancel} className="text-xs font-bold text-slate-500">Cancelar</button>}</div><label className="md:col-span-2"><Label>Descrição</Label><Input required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label><Label>Valor</Label><MoneyInput required value={form.amount} onValueChange={amount=>setForm({...form,amount})}/></label><label><Label>Tipo</Label><Select value={form.type} onChange={e=>setForm({...form,type:e.target.value as TransactionType,categories:[]})}><option value="INCOME">Receita</option><option value="EXPENSE">Despesa</option></Select></label><div className="md:col-span-2"><Label>Categoria(s)</Label><CategoryMultiSelect institutional={institutional} type={form.type} value={form.categories} onChange={categories=>setForm({...form,categories})} customItems={customItems}/></div><label><Label>Conta financeira</Label><Select value={form.account_id} onChange={e=>setForm({...form,account_id:e.target.value})}><option value="">Sem conta vinculada</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name} · {currency.format(Number(a.current_balance))}</option>)}</Select></label><label><Label>Forma de pagamento</Label><Select value={form.payment_method} onChange={e=>setForm({...form,payment_method:e.target.value})}><option value="PIX">PIX</option><option value="DEBIT">Débito</option><option value="CASH">Dinheiro</option><option value="TRANSFER">Transferência</option><option value="BOLETO">Boleto</option><option value="OTHER">Outro</option></Select></label>{institutional&&<label><Label>Centro de custo</Label><Input value={form.cost_center} onChange={e=>setForm({...form,cost_center:e.target.value})}/></label>}<label><Label>Data</Label><Input type="date" required value={form.occurred_on} onChange={e=>setForm({...form,occurred_on:e.target.value})}/></label><label className={institutional?"":"md:col-span-2"}><Label>Observação</Label><Textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="md:col-span-2"><Button type="submit" className="w-full" disabled={saving}>{saving?"Salvando...":"Salvar"}</Button></div></form>}
function Mini({label,value,tone}:{label:string;value:number;tone:"green"|"red"|"gold"}){const cls=tone==="green"?"text-emerald-700":tone==="red"?"text-rose-700":"text-[#8b6926]";return <div className="rounded-2xl border border-slate-100 bg-white p-4"><p className="text-xs font-bold text-slate-400">{label}</p><p className={`mt-2 text-xl font-black ${cls}`}>{currency.format(value)}</p></div>}
function Detail({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-slate-100 bg-slate-50 p-4"><p className="text-xs font-black uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 font-bold text-slate-900">{value}</p></div>}
function Label({children}:{children:React.ReactNode}){return <span className="mb-1.5 block text-xs font-bold uppercase tracking-wide text-slate-500">{children}</span>}
