"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import {ShieldAlert,Trash2,KeyRound} from "lucide-react";
import {useAuth} from "@/context/AuthContext";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Input} from "@/components/ui/input";
import {Select} from "@/components/ui/select";

const names:Record<string,string>={DAY:"Hoje",MONTH:"Mês atual",HALF_YEAR:"Semestre atual",YEAR:"Ano atual",RANGE:"Período personalizado",ALL:"Todos os dados financeiros"};
export default function SecurityResetPage(){
 const router=useRouter();const {session,signOut}=useAuth();const [scope,setScope]=useState("MONTH"),[start,setStart]=useState(""),[end,setEnd]=useState(""),[confirm,setConfirm]=useState(""),[aware,setAware]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function reauthenticate(){await signOut();router.replace("/login?next=/dashboard/seguranca-reset")}
 async function reset(){if(!session)return;setBusy(true);setMessage("");try{const r=await fetch("/api/security/reset-financial",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({scope,start,end,confirmation:confirm})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Não foi possível realizar o reset.");setMessage("Reset concluído. Snapshot de segurança criado e saldos recalculados.");setConfirm("");setAware(false)}catch(e:any){setMessage(e?.message||"Falha no reset.")}finally{setBusy(false)}}
 const ready=aware&&confirm==="RESETAR"&&(scope!=="RANGE"||(start&&end));
 return <div className="space-y-6"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#9b772c]">Área protegida</p><h1 className="mt-2 text-3xl font-black">Segurança e reset financeiro</h1><p className="mt-2 max-w-3xl text-sm text-slate-500">Limpe dados de teste ou períodos financeiros com proteção adicional. Antes da exclusão, o sistema cria um snapshot e depois recalcula contas e faturas.</p></div><Card className="border-rose-200"><CardHeader><CardTitle className="flex items-center gap-2 text-rose-800"><ShieldAlert className="size-5"/>Operação crítica</CardTitle></CardHeader><CardContent className="space-y-5"><label><span className="mb-1.5 block text-xs font-black uppercase text-slate-500">Período a limpar</span><Select value={scope} onChange={e=>setScope(e.target.value)}>{Object.entries(names).map(([k,v])=><option key={k} value={k}>{v}</option>)}</Select></label>{scope==="RANGE"&&<div className="grid gap-4 md:grid-cols-2"><Input type="date" value={start} onChange={e=>setStart(e.target.value)}/><Input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></div>}<div className="rounded-2xl bg-amber-50 p-4 text-sm text-amber-900"><b>{names[scope]}.</b> Serão apagadas movimentações do período. Seu usuário permanece cadastrado. Contas terão os saldos recalculados e as faturas afetadas serão reorganizadas.</div><Button type="button" variant="outline" className="w-full" onClick={()=>void reauthenticate()}><KeyRound className="size-4"/>Confirmar identidade com minha senha</Button><label><span className="mb-1.5 block text-xs font-black uppercase text-slate-500">Confirmação final</span><Input value={confirm} onChange={e=>setConfirm(e.target.value.toUpperCase())} placeholder="Digite RESETAR"/></label><label className="flex items-start gap-3 rounded-xl border p-4"><input type="checkbox" className="mt-1" checked={aware} onChange={e=>setAware(e.target.checked)}/><span className="text-sm">Estou ciente de que esta ação altera informações financeiras.</span></label>{message&&<div className="rounded-xl bg-slate-100 p-3 text-sm">{message}</div>}<Button type="button" disabled={!ready||busy} onClick={()=>void reset()} className="w-full bg-rose-700 hover:bg-rose-800"><Trash2 className="size-4"/>{busy?"Processando...":"Confirmar reset financeiro"}</Button></CardContent></Card></div>
}
