import * as XLSX from "xlsx";

export type ParsedBankRow={date:string;description:string;amount:number;externalId?:string;category:string;merchant:string;fingerprint:string};

const norm=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
const isoDate=(v:any)=>{if(v instanceof Date&&!isNaN(v.getTime()))return v.toISOString().slice(0,10);const s=String(v??"").trim();const br=s.match(/^(\d{2})[\/-](\d{2})[\/-](\d{4})/);if(br)return `${br[3]}-${br[2]}-${br[1]}`;const ofx=s.match(/^(\d{4})(\d{2})(\d{2})/);if(ofx)return `${ofx[1]}-${ofx[2]}-${ofx[3]}`;const d=new Date(s);return isNaN(d.getTime())?"":d.toISOString().slice(0,10)};
const num=(v:any)=>{if(typeof v==="number")return v;const s=String(v??"").trim().replace(/R\$/gi,"").replace(/\s/g,"");if(!s)return 0;if(s.includes(","))return Number(s.replace(/\./g,"").replace(",","."))||0;return Number(s)||0};
const category=(d:string)=>{const s=norm(d);if(/assai|atacadao|supermerc|mercado|carrefour/.test(s))return"Supermercado";if(/shell|ipiranga|posto|petrobras/.test(s))return"Combustível";if(/ifood|restaurante|lanchonete|pizza/.test(s))return"Alimentação";if(/uber|99 |taxi/.test(s))return"Transporte";if(/farmacia|drogasil|drogaria/.test(s))return"Saúde";if(/enel|energia|luz/.test(s))return"Energia";if(/internet|claro|vivo|tim/.test(s))return"Internet e telefone";if(/netflix|spotify|prime|disney/.test(s))return"Assinaturas";return"Outros"};
const fp=(date:string,amount:number,description:string,externalId?:string)=>norm(`${externalId||""}|${date}|${amount.toFixed(2)}|${description}`);
const make=(date:any,description:any,amount:any,externalId?:any):ParsedBankRow|null=>{const d=isoDate(date),desc=String(description??"").trim(),a=num(amount);if(!d||!desc||!a)return null;return{date:d,description:desc,amount:a,externalId:externalId?String(externalId):undefined,category:category(desc),merchant:desc,fingerprint:fp(d,a,desc,externalId?String(externalId):undefined)}};

export async function parseBankFile(file:File):Promise<ParsedBankRow[]>{const ext=file.name.split('.').pop()?.toLowerCase();if(ext==='ofx')return parseOFX(await file.text());if(ext==='csv')return parseCSV(await file.text());if(ext==='xlsx'||ext==='xls'){const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true});const ws=wb.Sheets[wb.SheetNames[0]];return rowsFromObjects(XLSX.utils.sheet_to_json(ws,{defval:""}) as Record<string,any>[])}throw new Error("Formato não suportado. Use OFX, CSV, XLS ou XLSX.")}

function parseOFX(text:string){const blocks=text.match(/<STMTTRN>[\s\S]*?<\/STMTTRN>/gi)||text.match(/<STMTTRN>[\s\S]*?(?=<STMTTRN>|<\/BANKTRANLIST>)/gi)||[];return blocks.map(b=>make(tag(b,'DTPOSTED'),tag(b,'MEMO')||tag(b,'NAME')||'Movimentação',tag(b,'TRNAMT'),tag(b,'FITID'))).filter(Boolean) as ParsedBankRow[]}
function tag(block:string,name:string){return block.match(new RegExp(`<${name}>([^<\\r\\n]+)`,`i`))?.[1]?.trim()||""}
function parseCSV(text:string){const lines=text.replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean);if(lines.length<2)return[];const sep=lines[0].split(';').length>lines[0].split(',').length?';':',';const heads=splitCsv(lines[0],sep);return rowsFromObjects(lines.slice(1).map(l=>{const vals=splitCsv(l,sep);return Object.fromEntries(heads.map((h,i)=>[h,vals[i]??""]))}))}
function splitCsv(line:string,sep:string){const out:string[]=[];let cur="",q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(c===sep&&!q){out.push(cur.trim());cur=""}else cur+=c}out.push(cur.trim());return out}
function rowsFromObjects(rows:Record<string,any>[]){return rows.map(r=>{const entries=Object.entries(r);const find=(tests:RegExp[])=>entries.find(([k])=>tests.some(t=>t.test(norm(k))))?.[1];const date=find([/^data$/, /date/, /dt lanc/, /lancamento/]);const desc=find([/descricao/, /historico/, /memo/, /estabelecimento/, /description/]);let amount=find([/^valor$/, /amount/, /valor lanc/]);if(amount===undefined){const credit=num(find([/credito/, /entrada/]));const debit=num(find([/debito/, /saida/]));amount=credit||-Math.abs(debit)}return make(date,desc,amount,find([/fitid/, /id trans/, /documento/]))}).filter(Boolean) as ParsedBankRow[]}
