"use client";
import { useState } from "react";
import { ArrowRight, CheckCircle2, ShieldCheck, Ticket } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Plan="PERSONAL"|"BUSINESS"|"MEDICAL";
const currency=(c:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(c/100);
export function ProductCheckout({plan,label,priceCents,enabled=true,className=""}:{plan:Plan;label:string;priceCents:number;enabled?:boolean;className?:string}){
 const [code,setCode]=useState(""),[coupon,setCoupon]=useState<{code:string;final:number;discount:number}|null>(null),[loading,setLoading]=useState(false),[validating,setValidating]=useState(false),[error,setError]=useState("");
 async function validate(){if(!code.trim())return;setValidating(true);setError("");try{const r=await fetch("/api/coupons/validate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({plan,coupon_code:code})});const j=await r.json();if(!r.ok){setCoupon(null);setError(j.error||"Cupom inválido.");return}setCoupon({code:j.code,final:j.final_amount,discount:j.discount_amount})}finally{setValidating(false)}}
 async function checkout(){setLoading(true);setError("");try{const r=await fetch("/api/payments/infinitepay/public-checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({plan,coupon_code:coupon?.code||code.trim()||undefined})});const j=await r.json();if(!r.ok){setError(j.error||"Não foi possível continuar.");return}if(!j.url){setError(j.error||"Não foi possível abrir o pagamento.");return}window.location.assign(j.url)}catch{setError("Não foi possível conectar ao checkout.")}finally{setLoading(false)}}
 return <div className={`rounded-[2rem] border border-black/5 bg-white p-6 shadow-[0_24px_70px_rgba(12,13,16,.08)] ${className}`}><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#9a762b]">Assinatura mensal</p><h3 className="mt-2 text-3xl font-black">{coupon?currency(coupon.final):currency(priceCents)}</h3>{coupon&&<p className="mt-1 text-xs text-slate-400 line-through">{currency(priceCents)}</p>}</div><span className="grid size-12 place-items-center rounded-2xl bg-[#c9a34d]/10 text-[#9a762b]"><ShieldCheck className="size-5"/></span></div><div className="mt-6"><p className="mb-2 text-xs font-black uppercase tracking-wide text-slate-500">Tem cupom?</p><div className="flex gap-2"><div className="relative flex-1"><Ticket className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><Input value={code} onChange={e=>{setCode(e.target.value.toUpperCase());setCoupon(null);setError("")}} placeholder="Digite seu cupom" className="pl-9"/></div><Button variant="outline" onClick={()=>void validate()} disabled={validating||!code.trim()}>{validating?"Validando...":"Aplicar"}</Button></div>{coupon&&<div className="mt-3 flex items-center gap-2 rounded-xl bg-emerald-50 p-3 text-xs font-bold text-emerald-700"><CheckCircle2 className="size-4"/>Cupom {coupon.code} aplicado · economia de {currency(coupon.discount)}</div>}{error&&<p className="mt-3 text-xs font-semibold text-rose-600">{error}</p>}</div>{enabled ? <><Button onClick={()=>void checkout()} disabled={loading} className="mt-6 h-14 w-full rounded-2xl bg-[#0d0f13] text-white hover:bg-black">{loading?"Abrindo pagamento...":label}<ArrowRight className="size-5"/></Button><p className="mt-3 text-center text-[11px] text-slate-400">Pagamento seguro pela InfinitePay. Acesso liberado após confirmação.</p></> : <><Button disabled className="mt-6 h-14 w-full rounded-2xl">Inscrições temporariamente pausadas</Button><p className="mt-3 text-center text-[11px] text-slate-400">Este plano está temporariamente indisponível.</p></>}</div>
}
