"use client";
import Link from "next/link";
import { usePathname,useRouter } from "next/navigation";
import { BarChart3,BriefcaseBusiness,CalendarDays,ChevronLeft,FileText,HeartPulse,Landmark,Menu,ReceiptText,Stethoscope,Target,UserRound,WalletCards,X } from "lucide-react";
import { useState } from "react";
import { useAuth } from "@/context/AuthContext";
import { MedicalProductGate } from "./MedicalProductGate";
import { cn } from "@/lib/utils";
const nav=[['Visão Geral','/medicos/dashboard',BarChart3],['Plantões','/medicos/plantoes',CalendarDays],['Vínculos','/medicos/vinculos',Landmark],['Particular','/medicos/particular',Stethoscope],['A Receber','/medicos/receber',ReceiptText],['Financeiro','/medicos/financeiro',WalletCards],['Investimentos','/medicos/investimentos',BriefcaseBusiness],['Carreira','/medicos/carreira',Target],['Relatórios','/medicos/relatorios',FileText]] as const;
export function MedicalAppShell({children}:{children:React.ReactNode}){const path=usePathname(),router=useRouter();const {profile}=useAuth();const [open,setOpen]=useState(false);return <MedicalProductGate><div className="min-h-screen bg-[#f5f7f9] text-[#102030]">{open&&<button className="fixed inset-0 z-40 bg-black/45 lg:hidden" onClick={()=>setOpen(false)}/>}<aside className={cn('fixed inset-y-0 left-0 z-50 flex w-[286px] flex-col bg-[#0b2031] text-white transition-transform lg:translate-x-0',open?'translate-x-0':'-translate-x-full')}><div className="flex h-24 items-center justify-between px-6"><Link href="/medicos/dashboard" className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-[#2f80b7]/15 text-[#77b9e8]"><HeartPulse className="size-5"/></span><div><strong className="block text-sm tracking-[.16em]">EQUITY ONE</strong><span className="text-[10px] uppercase tracking-[.18em] text-[#77b9e8]">Médicos</span></div></Link><button className="lg:hidden" onClick={()=>setOpen(false)}><X className="size-5"/></button></div><div className="mx-4 rounded-2xl border border-white/10 bg-white/[.05] p-4"><p className="text-xs text-slate-400">Perfil profissional</p><p className="mt-1 truncate text-sm font-bold">Dr. {profile?.full_name||'Usuário'}</p></div><nav className="flex-1 space-y-1 overflow-y-auto px-4 py-7">{nav.map(([label,href,Icon])=>{const a=path===href||path.startsWith(href+'/');return <Link key={href} href={href} onClick={()=>setOpen(false)} className={cn('flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold transition',a?'bg-[#2d79a9] text-white':'text-slate-400 hover:bg-white/[.06] hover:text-white')}><Icon className="size-5"/>{label}</Link>})}</nav><div className="border-t border-white/10 p-4"><Link href="/dashboard" className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-slate-400 hover:bg-white/[.06] hover:text-white"><ChevronLeft className="size-5"/>Equity One principal</Link></div></aside><div className="lg:pl-[286px]"><header className="sticky top-0 z-30 flex h-16 items-center border-b border-slate-200 bg-white/90 px-4 backdrop-blur lg:hidden"><button onClick={()=>setOpen(true)}><Menu className="size-5"/></button><span className="ml-4 text-sm font-black tracking-[.12em]">EQUITY ONE MÉDICOS</span></header><main className="mx-auto max-w-[1600px] p-4 md:p-8 lg:p-10">{children}</main></div></div></MedicalProductGate>}
