import Link from "next/link";
import {ArrowRight,BarChart3,BellRing,Building2,Check,ChevronRight,CreditCard,HeartPulse,Landmark,LineChart,LockKeyhole,Mail,MessageCircle,ReceiptText,ShieldCheck,Sparkles,Target,TrendingUp,UserRound,WalletCards} from "lucide-react";
import {Button} from "@/components/ui/button";
import {EquityOneLogo} from "@/components/EquityOneLogo";

export type LandingProduct={icon:"personal"|"business"|"medical";eyebrow:string;title:string;price:string;href:string;text:string;bullets:string[];cta:string};

type Props={products:LandingProduct[];supportEmail:string;whatsappHref:string};

const productIcons={personal:UserRound,business:Building2,medical:HeartPulse};
const ecosystem=[[Landmark,"Contas","Saldos, movimentações e transferências em contexto."],[CreditCard,"Cartões","Compras, parcelas, limites e faturas conectadas."],[ReceiptText,"Lançamentos","Receitas e despesas organizadas com clareza."],[Target,"Metas","Objetivos acompanhados com evolução financeira real."],[BarChart3,"Relatórios","Uma leitura mais útil do mês e das categorias."],[Sparkles,"IA","Registre e consulte sua rotina em linguagem natural."]] as const;

export function DarkLandingPage({products,supportEmail,whatsappHref}:Props){return <main className="min-h-screen overflow-hidden bg-[#07090c] text-white">
 <header className="sticky top-0 z-50 border-b border-white/[.07] bg-[#080a0e]/90 backdrop-blur-xl"><div className="mx-auto flex h-[112px] max-w-[1500px] items-center justify-between px-5 md:px-8 lg:px-12"><Link href="/" className="flex items-center"><EquityOneLogo priority className="h-[110px] w-auto md:h-[128px]"/></Link><nav className="hidden items-center gap-8 text-sm font-semibold text-slate-300 lg:flex"><a href="#problema" className="hover:text-[#e1bd65]">Por que Equity One</a><a href="#ecossistema" className="hover:text-[#e1bd65]">Ecossistema</a><a href="#plataforma" className="hover:text-[#e1bd65]">Plataforma</a><a href="#solucoes" className="hover:text-[#e1bd65]">Soluções</a><a href="#suporte" className="hover:text-[#e1bd65]">Suporte</a></nav><Link href="/login"><Button className="h-12 rounded-xl border border-[#d6ae4e]/60 bg-gradient-to-b from-[#f1d47d] to-[#c89935] px-6 font-black text-black hover:brightness-105">Já sou cliente <ArrowRight className="size-4"/></Button></Link></div></header>

 <section className="relative overflow-hidden border-b border-white/[.07]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_12%_60%,rgba(203,154,47,.14),transparent_25%),radial-gradient(circle_at_76%_16%,rgba(214,174,78,.09),transparent_28%)]"/><div className="relative mx-auto grid max-w-[1500px] gap-12 px-5 py-14 md:px-8 lg:grid-cols-[.84fr_1.16fr] lg:items-center lg:px-12">
  <div><div className="inline-flex items-center gap-2 rounded-full border border-[#d4ad55]/45 bg-[#d4ad55]/5 px-4 py-2 text-[11px] font-black uppercase tracking-[.19em] text-[#e1bd65]"><Sparkles className="size-4"/>Plataforma de gestão financeira inteligente</div><h1 className="mt-7 max-w-2xl text-[3.6rem] font-black leading-[.94] tracking-[-.055em] sm:text-6xl lg:text-[5.2rem]">Clareza hoje.<br/><span className="bg-gradient-to-r from-[#f4db92] via-[#d9ad4c] to-white bg-clip-text text-transparent">Controle sempre.</span></h1><p className="mt-7 max-w-xl text-base leading-7 text-slate-400 md:text-lg">Organize receitas, despesas, contas, cartões, metas e decisões em um só lugar. Tenha visão do que importa agora e do que vem pela frente.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="#solucoes"><Button className="h-14 rounded-xl bg-gradient-to-b from-[#efd078] to-[#c79431] px-7 text-base font-black text-black hover:brightness-105">Começar agora <ArrowRight className="size-5"/></Button></a><a href="#plataforma"><Button variant="outline" className="h-14 rounded-xl border-white/15 bg-white/[.03] px-7 text-base font-bold text-white hover:bg-white/[.07] hover:text-white">Ver como funciona <ChevronRight className="size-4"/></Button></a></div><div className="mt-8 overflow-hidden rounded-2xl border border-white/[.09] bg-white/[.035]"><div className="grid sm:grid-cols-[1.35fr_.65fr]"><div className="flex items-center gap-4 border-b border-white/[.07] p-5 sm:border-b-0 sm:border-r"><span className="grid size-11 place-items-center rounded-xl bg-[#d4ad55]/10 text-[#e1bd65]"><Sparkles className="size-5"/></span><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#e1bd65]">Uma marca. Três experiências.</p><p className="mt-1 text-xs leading-5 text-slate-400">Pessoal, Negócios e Médicos dentro do mesmo padrão de inteligência financeira.</p></div></div><div className="grid grid-cols-3 divide-x divide-white/[.07] text-center text-xs text-slate-300">{[[UserRound,"Pessoal"],[Building2,"Negócios"],[HeartPulse,"Médicos"]].map(([Icon,label]:any)=><div key={label} className="grid place-items-center gap-2 p-4"><Icon className="size-5 text-[#d4ad55]"/><b>{label}</b></div>)}</div></div></div></div>
  <HeroDashboard/>
 </div><div className="relative mx-auto max-w-[1500px] px-5 pb-12 md:px-8 lg:px-12"><div className="grid overflow-hidden rounded-2xl border border-[#d4ad55]/25 bg-[#0d1015] md:grid-cols-4">{[[ShieldCheck,"Segurança e privacidade","Autenticação e áreas privadas por usuário."],[Landmark,"Tudo conectado","Contas, cartões, lançamentos e metas no mesmo fluxo."],[Target,"Decisões mais inteligentes","Contexto para enxergar melhor o mês."],[LockKeyhole,"Você no controle","Seus registros, seus acessos e suas decisões."]].map(([Icon,title,text]:any,i)=><div key={title} className={`flex gap-4 p-5 ${i<3?"md:border-r md:border-white/[.07]":""}`}><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-[#d4ad55]/10 text-[#e1bd65]"><Icon className="size-5"/></span><div><p className="text-sm font-black">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></div></div>)}</div></div></section>

 <section id="problema" className="mx-auto max-w-[1500px] px-5 py-20 md:px-8 lg:px-12"><div className="grid gap-8 lg:grid-cols-[.78fr_1.22fr] lg:items-end"><div><p className="text-xs font-black uppercase tracking-[.22em] text-[#d4ad55]">O problema real</p><h2 className="mt-4 text-4xl font-black tracking-[-.04em] md:text-5xl">Você não precisa de mais números. <span className="text-slate-500">Precisa de visão.</span></h2></div><p className="max-w-2xl text-base leading-7 text-slate-400 lg:ml-auto">O Equity One reduz o caminho entre registrar uma movimentação e entender o impacto dela na sua vida, negócio ou carreira.</p></div><div className="mt-10 grid gap-4 lg:grid-cols-3">{[[WalletCards,"Dinheiro espalhado vira decisão no escuro.","Contas, cartões e compromissos precisam conversar para o saldo fazer sentido."],[BellRing,"O problema não deveria aparecer depois do vencimento.","Prioridades precisam chegar antes, não depois da urgência."],[LineChart,"Extrato mostra o passado. Gestão ajuda no próximo passo.","Contexto transforma movimentação em decisão."]].map(([Icon,title,text]:any)=><article key={title} className="rounded-[1.8rem] border border-white/[.08] bg-white/[.035] p-7 transition hover:-translate-y-1 hover:border-[#d4ad55]/25"><span className="grid size-12 place-items-center rounded-2xl bg-[#d4ad55]/10 text-[#e1bd65]"><Icon className="size-5"/></span><h3 className="mt-6 text-xl font-black leading-7">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{text}</p></article>)}</div></section>

 <section id="ecossistema" className="border-y border-white/[.07] bg-[#0a0c10]"><div className="mx-auto max-w-[1500px] px-5 py-20 md:px-8 lg:px-12"><p className="text-xs font-black uppercase tracking-[.22em] text-[#d4ad55]">Ecossistema Equity One</p><h2 className="mt-4 max-w-3xl text-4xl font-black tracking-[-.04em] md:text-5xl">Tudo conversa. Nada parece uma tela isolada.</h2><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{ecosystem.map(([Icon,title,text])=><div key={title} className="group rounded-[1.7rem] border border-white/[.08] bg-white/[.035] p-6 transition hover:-translate-y-1 hover:border-[#d4ad55]/25"><div className="flex justify-between"><span className="grid size-11 place-items-center rounded-xl bg-[#d4ad55]/10 text-[#e1bd65]"><Icon className="size-5"/></span><ChevronRight className="size-4 text-slate-700 group-hover:text-[#d4ad55]"/></div><h3 className="mt-5 text-xl font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></div>)}</div></div></section>

 <section id="plataforma" className="mx-auto max-w-[1500px] px-5 py-20 md:px-8 lg:px-12"><div className="grid gap-8 lg:grid-cols-[.72fr_1.28fr] lg:items-end"><div><p className="text-xs font-black uppercase tracking-[.22em] text-[#d4ad55]">Veja a plataforma</p><h2 className="mt-4 text-4xl font-black tracking-[-.04em] md:text-5xl">Mais conexão. Menos caça à informação.</h2></div><p className="max-w-2xl text-base leading-7 text-slate-400 lg:ml-auto">Contas, cartões, faturas, lançamentos, metas e IA trabalham dentro da mesma experiência para reduzir cliques desnecessários.</p></div><div className="mt-10"><HeroDashboard compact/></div></section>

 <section id="solucoes" className="border-y border-white/[.07] bg-[#0a0c10]"><div className="mx-auto max-w-[1500px] px-5 py-20 md:px-8 lg:px-12"><p className="text-xs font-black uppercase tracking-[.22em] text-[#d4ad55]">Escolha sua experiência</p><h2 className="mt-4 text-4xl font-black tracking-[-.04em] md:text-5xl">Um Equity One para cada rotina.</h2><div className="mt-10 grid gap-5 lg:grid-cols-3">{products.map(p=><ProductCard key={p.title} {...p}/>)}</div></div></section>

 <section id="suporte" className="bg-[#0d1015]"><div className="mx-auto grid max-w-[1500px] gap-8 px-5 py-14 md:px-8 lg:grid-cols-[.85fr_1.15fr] lg:items-center lg:px-12"><div><p className="text-xs font-black uppercase tracking-[.22em] text-[#d4ad55]">Suporte Equity One</p><h2 className="mt-3 text-3xl font-black md:text-4xl">Precisou de ajuda? Fale diretamente com o suporte.</h2><p className="mt-4 text-sm leading-6 text-slate-400">Dúvidas sobre acesso, assinatura e uso da plataforma podem ser tratadas pelos canais oficiais.</p></div><div className="grid gap-3 sm:grid-cols-2"><SupportCard icon={MessageCircle} title="WhatsApp" text="Abrir conversa com o suporte" href={whatsappHref}/><SupportCard icon={Mail} title="E-mail" text={supportEmail} href={`mailto:${supportEmail}`}/></div></div></section>

 <footer className="border-t border-white/[.07] bg-[#050609] text-slate-500"><div className="mx-auto max-w-[1500px] px-5 py-10 md:px-8 lg:px-12"><div className="grid gap-8 border-b border-white/[.07] pb-8 md:grid-cols-[1.2fr_.8fr_.8fr]"><div><EquityOneLogo className="h-[105px] w-auto"/><p className="mt-3 max-w-sm text-sm leading-6">Gestão financeira com identidade, contexto e decisão.</p></div><div><p className="text-xs font-black uppercase tracking-[.18em] text-white">Navegação</p><div className="mt-4 space-y-3 text-sm"><a href="#plataforma" className="block hover:text-white">Plataforma</a><a href="#solucoes" className="block hover:text-white">Soluções</a><Link href="/login" className="block hover:text-white">Entrar</Link></div></div><div><p className="text-xs font-black uppercase tracking-[.18em] text-white">Atendimento</p><div className="mt-4 space-y-3 text-sm"><a href={whatsappHref} target="_blank" rel="noreferrer" className="block hover:text-white">WhatsApp</a><a href={`mailto:${supportEmail}`} className="block hover:text-white">{supportEmail}</a></div></div></div><div className="flex flex-col gap-3 pt-6 text-xs md:flex-row md:justify-between"><p>© {new Date().getFullYear()} Equity One. Todos os direitos reservados.</p><p>Organize. Entenda. Decida.</p></div></div></footer>
 </main>}

function HeroDashboard({compact=false}:{compact?:boolean}){return <div className="rounded-[2rem] border border-[#d4ad55]/35 bg-[#0b0e12] p-3 shadow-[0_35px_100px_rgba(0,0,0,.48)] md:p-4"><div className={`overflow-hidden rounded-[1.5rem] border border-white/[.07] ${compact?"p-5 md:p-7":"grid min-h-[555px] lg:grid-cols-[104px_1fr]"}`}>{!compact&&<aside className="hidden border-r border-white/[.07] bg-[#090b0f] p-4 lg:block"><EquityOneLogo className="mx-auto h-16 w-auto"/><div className="mt-7 space-y-3">{[Landmark,BarChart3,Target,CreditCard,LineChart].map((Icon,i)=><div key={i} className={`grid h-11 place-items-center rounded-xl ${i===0?"bg-[#d4ad55]/15 text-[#e1bd65]":"text-slate-600"}`}><Icon className="size-5"/></div>)}</div></aside>}<div className={compact?"":"p-4 md:p-6"}><div className="flex justify-between gap-4"><div><p className="text-xs font-black text-[#d4ad55]">Visão geral</p><h3 className="mt-2 text-2xl font-black">Bom dia. Aqui está seu panorama.</h3><p className="mt-1 text-xs text-slate-500">Uma leitura rápida do que importa agora.</p></div><span className="h-fit rounded-xl border border-white/[.08] bg-white/[.03] px-3 py-2 text-xs text-slate-400">Este mês</span></div><div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Saldo disponível","R$ 8.420,00"],["A receber","R$ 4.180,00"],["Despesas do mês","R$ 4.240,00"],["Meta do mês","82%"]].map(([a,b])=><div key={a} className="rounded-2xl border border-white/[.08] bg-white/[.035] p-4"><p className="text-[11px] text-slate-500">{a}</p><p className="mt-2 text-lg font-black">{b}</p></div>)}</div><div className="mt-4 grid gap-4 lg:grid-cols-[1.3fr_.7fr]"><div className="rounded-2xl border border-white/[.08] bg-white/[.03] p-4"><div className="flex justify-between"><p className="text-sm font-black">Evolução do resultado</p><TrendingUp className="size-4 text-[#d4ad55]"/></div><div className="mt-6 flex h-36 items-end gap-2">{[22,34,40,52,49,61,70,68,82,94].map((h,i)=><span key={i} className="flex-1 rounded-t bg-gradient-to-t from-[#7b5a1f] to-[#e1bd65]" style={{height:`${h}%`}}/>)}</div></div><div className="rounded-2xl border border-white/[.08] bg-white/[.03] p-4"><p className="text-sm font-black">Distribuição de despesas</p><div className="mx-auto mt-6 grid size-32 place-items-center rounded-full border-[18px] border-[#d4ad55] shadow-[inset_0_0_0_10px_#23262b]"><span className="text-xl font-black">100%</span></div></div></div><div className="mt-4 flex items-center justify-between rounded-2xl border border-[#d4ad55]/20 bg-[#d4ad55]/10 p-4"><div className="flex gap-3"><BellRing className="size-5 text-[#e1bd65]"/><div><p className="text-sm font-black text-[#e1bd65]">Você não deveria precisar procurar o problema.</p><p className="mt-1 text-xs text-slate-500">Vencimentos e prioridades aparecem no contexto certo.</p></div></div><ChevronRight className="size-4 text-[#d4ad55]"/></div></div></div></div>}

function ProductCard({icon,eyebrow,title,price,href,text,bullets,cta}:LandingProduct){const Icon=productIcons[icon];return <article className="flex h-full flex-col rounded-[2rem] border border-white/[.08] bg-white/[.035] p-7 transition hover:-translate-y-1 hover:border-[#d4ad55]/25"><div className="flex justify-between"><span className="grid size-12 place-items-center rounded-2xl bg-[#d4ad55]/10 text-[#e1bd65]"><Icon className="size-6"/></span><div className="text-right"><p className="text-[10px] uppercase text-slate-600">a partir de</p><p className="mt-1 text-xl font-black">{price}<span className="text-xs text-slate-600">/mês</span></p></div></div><p className="mt-7 text-[10px] font-black uppercase tracking-[.18em] text-[#d4ad55]">{eyebrow}</p><h3 className="mt-2 text-2xl font-black">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{text}</p><div className="mt-6 space-y-3">{bullets.map(x=><div key={x} className="flex gap-3 text-sm text-slate-300"><Check className="size-4 text-[#d4ad55]"/><span>{x}</span></div>)}</div><Link href={href} className="mt-auto pt-8"><Button className="h-13 w-full rounded-xl bg-gradient-to-b from-[#efd078] to-[#c79431] font-black text-black hover:brightness-105">{cta}<ChevronRight className="size-4"/></Button></Link></article>}
function SupportCard({icon:Icon,title,text,href}:{icon:any;title:string;text:string;href:string}){return <a href={href} target={href.startsWith("http")?"_blank":undefined} rel={href.startsWith("http")?"noreferrer":undefined} className="flex items-center gap-3 rounded-2xl border border-white/[.08] bg-white/[.035] p-4 hover:border-[#d4ad55]/30"><span className="grid size-11 place-items-center rounded-xl bg-[#d4ad55]/10 text-[#e1bd65]"><Icon className="size-5"/></span><div className="min-w-0 flex-1"><p className="font-black">{title}</p><p className="mt-1 truncate text-xs text-slate-500">{text}</p></div><ChevronRight className="size-4 text-slate-700"/></a>}
